### ISSUE TITLE
GitLab logo deviates too far

### ISSUE THREAD

**Issue by sanmai-NL** [edent/SuperTinyIcons#105]
[The official GitLab company logo](https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo.svg), from  [the official GitLab branding](https://about.gitlab.com/press/).
[Your rendition of the GitLab company logo.](https://github.com/edent/SuperTinyIcons/blob/6438f6f2ee6b322269f5fe1c004e653fe30d3f87/images/svg/gitlab.svg)

The differences are too stark IMO. Can the official logo still be compressed effectively, even lossily if needed, while retaining the distinguishing features, such as the palette?

**Comment by arturoacevedob** [comment]
I agree with you.

I'm revising and optimizing every icon and just yesterday I did what you said.

The result was 447 bytes, so yes!

**Comment by edent** [comment]
Looking forward to seeing the update :-)

**Comment by edent** [comment]
Fixed in #112
