### ISSUE TITLE
Wanted: Icons for music social sites like Holonis, Fanburst

### ISSUE THREAD

**Issue by danwood** [edent/SuperTinyIcons#107]
## The icon I want is:
* Name: Holonis
* URL: https://www.holonis.com
* Link to icon: https://process.fs.holonis.com/9Q5SWGYxRzqTblJRkruw https://yt3.ggpht.com/-PNZlW5-4lRk/AAAAAAAAAAI/AAAAAAAAAAA/5BMv9tlMFuY/s900-c-k-no-mo-rj-c0xffffff/photo.jpg

* Vector version of the logo: Not found
* Official style guide or brand guide: Not found

## The icon I want is:
* Name: Fanburst
* URL: https://fanburst.com
* Link to icon: https://fanburst-a.freetls.fastly.net/assets/fb_logo-d21d7c29507de764cd5906202ee16bc1e7917473ee12de9b402c4080e91a870a.png https://fanburst-a.freetls.fastly.net/assets/fanburst-icon-e4c049347488392169b94e92ac140deef90e40ea0a00a705775500608e78018e.png  

* Vector version of the logo: Not found
* Official style guide or brand guide: Not found

**Comment by edent** [comment]
Thanks Dan. Ideally we're looking for popular services - these two don't appear to meet that criteria. Sorry.
