### ISSUE TITLE
Wanted: Plex

### ISSUE THREAD

**Issue by Fish2** [edent/SuperTinyIcons#108]
## The icon I want is:

* Name: Plex
* URL: https://www.plex.tv
* Link to icon: https://images-na.ssl-images-amazon.com/images/I/61hfQoL4mkL.png

* Vector version of the logo:
* Official style guide or brand guide:

**Comment by edent** [comment]
http://brand.plex.tv/d/qxmJ3odkK0fj/plex-style-guide
