### ISSUE TITLE
Compression of hex colour

### ISSUE THREAD

**Issue by Fish2** [edent/SuperTinyIcons#113]
Compression of hex colour might be worth looking in to 

https://gist.github.com/Prinzhorn/2628611

**Comment by edent** [comment]
Sounds good! Do it 😀

**Comment by Fish2** [comment]
@edent The only trouble is some colours have a big difference and others don't. It all depends on the hex so would need to make a decision on each one whether it's a close enough match.

interestingly some one on that post has made some code to run on a site which can give you a visual guide as to what i mean http://jsfiddle.net/yckart/qxUkj/

**Comment by edent** [comment]
I've taken a look through the current icons and compressed them where possible. Thanks.
