### ISSUE TITLE
Request - Viber

### ISSUE THREAD

**Issue by greatramses** [edent/SuperTinyIcons#124]
## The icon I want is:

* Name: viber
* URL: https://www.viber.com
* Link to icon: i don't now :(

* Vector version of the logo:
* Official style guide or brand guide:

**Comment by evanre** [comment]
Hi, here is official vector logos in [Google Drive](https://drive.google.com/drive/u/0/folders/0Bw5wFi2tTCqfeEMwU2xza1hyNGM)

**Comment by edent** [comment]
From that link, there's a PNG version of the icon. Can anyone find a Vector?
![iconpurple](https://user-images.githubusercontent.com/837136/35558079-fe1c8086-059e-11e8-9558-4ff209651bee.png)

**Comment by evanre** [comment]
@eden, Hi, the "Logo assets.ai" file contains this logo. I've created svg version, but it weights 2.5kb 
Maybe you can help =)
<img src="https://svgshare.com/i/5Gp.svg">

**Comment by edent** [comment]
Best I can do so far is 1,217 bytes.

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="Viber" role="img"
viewBox="0 0 512 512"
fill="#665ca7"><rect
width="512" height="512"
rx="15%"
fill="#fff"/><path d="m403 95c-10-9-50-38-140-39 0 0-106-6-157 41-29 29-39 71-40 123s-2 149 92 175v41s-1 16 10 19c13 4 21-8 33-22l23-26c64 6 114-7 119-9 13-4 87-13 99-111 12-100-6-163-39-192zm11 185c-11 82-70 87-81 90-5 2-48 13-103 9 0 0-40 49-53 62-2 2-4 3-6 2-2 0-2-3-2-7v-67c-80-22-75-105-74-148s9-79 33-103c44-39 133-33 133-33 76 0 112 23 121 30 28 24 42 82 32 165z"/><path d="m300 223c-3 0-5-3-5-5-1-17-9-26-26-27a5 5 0 0 1 1-10c22 1 34 14 35 36 0 3-2 5-5 5z"/><path d="m326 231c-3 0-5-2-5-5 0-17-5-31-15-43a63 63 0 0 0 -44-19c-3 0-5-3-5-5 0-3 3-5 5-5 22 2 39 9 51 22 12 14 18 30 18 50 0 3-2 5-5 5z"/><path d="m352 242c-2 0-5-3-5-5 0-31-9-55-27-73a94 94 0 0 0 -67-26 5 5 0 0 1 0-10c29 0 54 10 74 29s30 46 30 79c1 3-2 6-5 6zm-81 43s7 1 11-4l7-9c4-5 12-8 21-3a208 208 0 0 1 36 26c5 4 6 11 3 18-4 7-9 14-16 20-5 4-11 7-16 7h-2l-7-1c-8-2-21-8-43-20a258 258 0 0 1 -53-39h-1v-1a29588 29588 0 0 1 -16-17c-8-10-16-22-24-37-12-22-18-35-20-43a22 22 0 0 1 -1-9c0-6 3-11 7-16 6-7 13-12 20-16s14-2 18 3a507 507 0 0 0 26 36c5 9 2 17-3 21l-9 7c-5 4-4 11-4 11s14 53 66 66z"/></svg>
```

**Comment by baybal** [comment]
#128 done

**Comment by rumyantsekov** [comment]
Guys, I need button for my website. Am I allowed to use the icon purple-04.svg from the Google Drive?

**Comment by edent** [comment]
@rumyantsekov here's the tiny one we made - https://github.com/edent/SuperTinyIcons/blob/master/images/svg/viber.svg - you can use that if you want.

**Comment by rumyantsekov** [comment]
Thanks!
