### ISSUE TITLE
Printer Icon

### ISSUE THREAD

**Issue by leocaseiro** [edent/SuperTinyIcons#138]
## The icon I want is:

* Name: printer
* URL: https://www.iconfinder.com/icons/326675/print_icon
* Link to icon: https://www.iconfinder.com/icons/326675/print_icon#size=512

* Vector version of the logo: https://www.iconfinder.com/icons/326675/print_icon#size=512
* Official style guide or brand guide: any

**Comment by edent** [comment]
Fixed in #235
