### ISSUE TITLE
Keybase: missing path (?) + alt version + gitlab background color

### ISSUE THREAD

**Issue by Alex131089** [edent/SuperTinyIcons#144]
Hello, 

https://github.com/edent/SuperTinyIcons/blob/master/images/svg/keybase.svg seems to have a missing path (the round face) from the [original version](https://github.com/keybase/client/blob/master/shared/images/iconfont/kb-iconfont-keybase-16.svg), or is that wanted?
When I open the source in Inkscape the same part is missing, but not in Chrome. By manually removing the href&co parts from the source it seems to open correctly (at least there's more paths shown, I didn't verify if I broke something else).

I made my own version, based on https://commons.wikimedia.org/wiki/File:Keybase_logo_official.svg, with colors, but it isn't under 1k sadly (I used https://jakearchibald.github.io/svgomg/. Maybe it can be more optimized.
[keybase.zip](https://github.com/edent/SuperTinyIcons/files/1798589/keybase.zip)

On a side note, I gave Gitlab a try myself in the past, and instead of white (which I think doesn't fit with Gitlab, as they're often using the logo on a violet background), I used the same color as in https://about.gitlab.com/press/ for the background, `#30353e` (my version it 833B at best though).

Thanks for the icons,

**Comment by edent** [comment]
Hi! Thanks for the note. I removed the round face because it was the only way to get it under 1KB.  I'll take a look at yours and see if it can be shrunk.

You're welcome to send a pull request for the GitLab one if you like.

**Comment by edent** [comment]
Closed in #146

**Comment by Alex131089** [comment]
Not the Keybase part :p
