### ISSUE TITLE
QQ Icon - help wanted

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#150]
Best I can do is 1,077 Bytes.

```
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="qq" role="img"
viewBox="0 0 512 512"><g fill="#ffc107"><ellipse cx="194" cy="398" rx="57" ry="32"/><ellipse cx="318" cy="398" rx="57" ry="32"/></g><path d="m377 229c-5-17-2-40-3-56 0-61-53-111-118-111s-119 50-119 111c-2 18 3 40-2 56-18 25-35 55-35 78 0 44 13 40 13 40 5 0 15-9 23-20 19 55 65 93 120 93s101-38 120-93c8 11 18 20 23 20 0 0 13 4 13-40 0-23-17-54-35-78z" fill="#37474f"/><path d="m171 237c-23 66 35 166 85 165 50 0 105-98 85-165z" fill="#eceff1"/><g fill="#fff"><ellipse cx="224" cy="150" rx="23" ry="33"/><ellipse cx="288" cy="150" rx="23" ry="33"/></g><g fill="#37474f"><path d="m284 136c-6 0-10 6-10 13 0 8 4-4 10-4 5 0 9 12 9 4 0-7-4-13-9-13z"/><ellipse cx="228" cy="149" rx="10" ry="14"/></g><path d="m329 204c0 8-33 23-73 23s-73-15-73-23c0-7 33-13 73-13s73 6 73 13z" fill="#ffc107"/><path d="m391 220c-4-14-9-20-19-12 0 0-55 29-115 29v1-1c-61 0-115-29-115-29-10-7-15-2-19 12s-6 18 6 26l32 15c-6 32-5 63-5 65 1 13 12 12 27 12 14-1 26 0 26-15 0-8 0-27 3-46 15 3 29 5 46 5 67 0 126-35 127-36 11-7 9-11 6-26z" fill="#ff3d00"/></svg>
```

**Comment by baybal** [comment]
<svg xmlns="http://www.w3.org/2000/svg"
aria-label="qq" role="img"
viewBox="0 0 512 512"><path fill="#ffc107" d="M261 398a57 32 0 0 0 114 0 57 32 0 0 0-114 0zm-124 0a57 32 0 0 0 114 0 57 32 0 0 0-114 0z"/><path fill="#37474f" d="M238 149a10 14 0 0 1-20 0 10 14 0 0 1 20 0zm46-13c-6 0-10 6-10 13 0 8 4-4 10-4 5 0 9 12 9 4 0-7-4-13-9-13zm27 14a23 33 0 0 1-46 0 23 33 0 0 1 46 0zm-64 0a23 33 0 0 1-46 0 23 33 0 0 1 46 0zm127 79v-56a119 119 0 0 0-237 0v56c-18 25-35 55-37 78 0 44 13 40 13 40 5 0 15-9 23-20 19 55 65 93 120 93s101-38 120-93c8 11 18 20 23 20 0 0 13 4 13-40 0-23-17-54-37-78z"/><path fill="#ffc107" d="M183 204a73 13 0 1 1 146 0 73 23 0 1 1-146 0z"/><path fill="#eceff1" d="M171 237a88 132 0 1 0 170 0z"/><path fill="#ff3d00" d="M391 220c-4-14-9-20-19-12a235 225 0 0 1-230 0c-10-7-15-2-19 12s-6 18 6 26l32 15c-6 32-5 63-5 65 1 13 12 12 27 12 14-1 26 0 26-15 0-8 0-27 3-46 15 3 29 5 46 5 67 0 126-35 127-36 11-7 9-11 6-26z"/></svg>

**Comment by baybal** [comment]
@edent 940 , shave some extra anchro points, turn cubic splines to quadratic, and you can shave 100 more
