### ISSUE TITLE
Vegetarian Icon

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#151]
## The icon I want is:

* Name: Vegetarian Symbol -  Ⓥ

Note: **NOT** https://www.v-label.eu/

**Comment by edent** [comment]
Hmmm. Doesn't render in monospace in the browser. Weird!

**Comment by tonyraoul** [comment]
can you please add it as an image i can't find it

**Comment by edent** [comment]
@tonyraoul It's https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/vegetarian.svg?sanitize=true

I think the layout may be browser dependent.
