### ISSUE TITLE
Access logo file missing from references

### ISSUE THREAD

**Issue by edjw** [edent/SuperTinyIcons#158]
The International Symbol of Access logo file is missing from [the reference images](https://github.com/edent/SuperTinyIcons/blob/master/images/reference/index.md). There's a space for it but the image file is missing.

The source link ends up here:
[https://en.wikipedia.org/wiki/International_Symbol_of_Access#/media/File:MUTCD_D9-6.svg](https://en.wikipedia.org/wiki/International_Symbol_of_Access#/media/File:MUTCD_D9-6.svg)

**Comment by edent** [comment]
Thanks! It is in the reference directory as an SVG. Could you raise a pull request renaming it in the index file?
