### ISSUE TITLE
SVG size can be lower by running latest svgcleaner

### ISSUE THREAD

**Issue by devrck** [edent/SuperTinyIcons#162]
Hi,

I've tried just a couple of icons so far but I saw some more saving for example:

- gitlogo 5.54% lower
- twitter 5.77% lower
- flickr 12.4% lower

Maybe its a good idea just to try running svgcleaner on all of them.

**Comment by devrck** [comment]
Please check https://github.com/edent/SuperTinyIcons/compare/master...devrck:smallimprovement?expand=1 , since you've mentioned it I don't know if its ok.

**Comment by edent** [comment]
No. That's missing `aria-label="Flickr" role="img"`

Accessibility is not optional.

If you can find some other space savings, we'd love to have them.

**Comment by devrck** [comment]
I understand, thank you for the quick response. I will close the issue then.
