### ISSUE TITLE
StackExchange has a new logo (and the current one has a gradient)

### ISSUE THREAD

**Issue by jaller94** [edent/SuperTinyIcons#167]
## The icon I want is:

* Name: StackExchange
* URL: https://stackoverflow.com/company/
* Link to icon: https://stackoverflow.com/company/logos

* Vector version of the logo: https://cdn.sstatic.net/Sites/stackoverflow/company/img/logos/se/se-icon.svg?v=62f619494ccd
* Official style guide or brand guide: https://stackoverflow.com/legal/trademark-guidance

**Comment by edent** [comment]
Looks good. Thanks @baybal. And thank you @jaller94 for letting us know.

**Comment by jaller94** [comment]
The commit above did not update the logo inside the box nor did it remove the gradient.
I sent a pull request to update the colours and remove the gradient.
