### ISSUE TITLE
Re-generate the Android Drawables

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#189]
Use Android Vector Studio - https://developer.android.com/studio/write/vector-asset-studio#svg - to make sure all the SVGs can be used in Android projects.

**Comment by jmb** [comment]
This might help? https://www.npmjs.com/package/svg2vectordrawable

**Comment by alexanderadam** [comment]
It would be great if the icons could be minified as well because [the calendar](https://github.com/edent/SuperTinyIcons/blob/master/images/android-vector-drawable/calendar.xml) alone has over 9KB and line breaks / indention are probably not needed anyway.

**Comment by edent** [comment]
@alexanderadam sounds good - go for it!

**Comment by alexanderadam** [comment]
How are you generating those icons? I have no idea about Android development? Do you have a CI that is generating them? Or what's the current process?

**Comment by ace-dent** [comment]
While browsing the XML files, I found these issues/ inconsistencies:
1. First line for some files (converted more recently) is `<?xml version="1.0" encoding="utf-8"?>`. Is this required?
2. It's not clear if the filled background should be a rectangle *with* or *without* rounded corners. Most icons have no rounding (`"M0,0h512v512h-512z"`), but some have rounded corners baked in (`"M 15 0 L 497 0 Q 512 0 512 15 L 512 497 Q 512 512 497 512 L 15 512 Q 0 512 0 497 L 0 15 Q 0 0 15 0 Z"`). Guidance should be added to this project's documentation.
3. In some places path attributes (`android:fillColor`) come before or after the path data. This should be consistent.
4. Android guideline is that `android:width` and `android:height` should be <200dp.

Over arching question: why provide these files at all? There are numerous vector formats- why is this Android format treated specially? It seems better to maintain the SVG images as a canonical source and allow developers to convert them as required. IMHO.

**Comment by ace-dent** [comment]
On point (2)- Information is present in `README` that hasn't been updated in `CONTRIBUTING`. These two documents should be kept in sync.

**Comment by edent** [comment]
I've now updated both documents.
