### ISSUE TITLE
Terminal case, almost out of ideas - Apple Music

### ISSUE THREAD

**Issue by baybal** [edent/SuperTinyIcons#194]
Task - reduce size without breaking it on Safari...

What to do with it?

All hack tried before break Safari:
- #RGBA colour codes
- #RRGGBBAA colour codes
- Xmls namespace omission for xlink
- Gradient attributes omission
- CSS gradients
- CSS effects
- putting gradient on top of as solid fill

Can somebody who has access to Safari try again these tricks, and see if the latest version can tolerate any of those?

**Comment by edent** [comment]
Just tried on Safari and it seems to work as is....
![Screen Shot 2019-03-25 at 11 42 46](https://user-images.githubusercontent.com/837136/54917267-59ac6300-4ef3-11e9-8744-ee823dd1c05e.png)
![Screen Shot 2019-03-25 at 11 43 09](https://user-images.githubusercontent.com/837136/54917268-59ac6300-4ef3-11e9-80bb-9d27a07f72c0.png)

**Comment by baybal** [comment]
I mean if there is any way to reduce its prodigious size

**Comment by judeGibbons** [comment]
Mere tweaks, but putting the clippath at the start of the file and nesting path 'c' inside it (so removing 'use x:href="#c"') and rounding some of the linear gradient points (which barely makes a noticeable difference) can get it to 981 bytes.

**Comment by baybal** [comment]
Brought to acceptable size in the last commit
