### ISSUE TITLE
Elementary OS

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#230]
## The icon I want is:

* Name: Elementary OS
* URL: https://elementary.io/
* Link to icon: https://github.com/elementary/website/blob/master/_images/brand/logomark-white.svg

**Comment by lilivelazquezz** [comment]
Hello, Do you still need help with this?

**Comment by maxiwolleb** [comment]
Hey @edent, added everything stated in the contributing, hope it fits like this. Hope to contribute more to the projekt in the future(hopefully without all the hassle 😆 )
