### ISSUE TITLE
Routing Tiny Icon

### ISSUE THREAD

**Issue by AakbariP** [edent/SuperTinyIcons#238]
Plz add Icons for route and map

**Comment by edent** [comment]
Thanks AakbariP - do you have any example icons we can use as a template?

**Comment by adrienluitot** [comment]
Some nice bases : https://fontawesome.com/icons?d=gallery&q=map
(From a concurrent :scream: )

**Comment by Fmressel** [comment]
Just to be aware, Feather Icons has a pin icon that is 322 bytes and a map icon that is 373 bytes.
https://feathericons.com/?query=map

So maybe the map sign icon (seen in the first search result adrienluitot linked to) would be a good choice to give more options!

**Comment by romain-dartigues** [comment]
Would [OSGeo](https://www.osgeo.org) [icon](https://www.osgeo.org/wp-content/themes/roots/assets/img/logo-osgeo.svg) and [MapServer](https://mapserver.org/) [icon](https://mapserver.org/_static/banner.png) valid candidates?
As I have them but must make them fit in 1KiB...

**Comment by edent** [comment]
If they're popular & recognisable services, sure.

**Comment by edent** [comment]
No action after a year. Closing. Feel free to open a new issue if there's a specific service's icon you want.
