### ISSUE TITLE
add Semaphore CI

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#264]
## The icon I want is:

* Name: Semaphore CI
* URL: https://semaphoreci.com/
* Link to icon: https://seeklogo.com/vector-logo/273888/semaphore

**Comment by ryuakaa** [comment]
Please review pr #327.

**Comment by alexanderadam** [comment]
@ryuakaa it looks good to me but I'm not a maintainer of this project. :wink:
But so far it seems that reviews by **edent** are done in a very timely manner.

Thank you for your contribution!

**Comment by ryuakaa** [comment]
Thank you @alexanderadam and also @edent for reviewing my pr :smile:
