### ISSUE TITLE
add Ruby lang

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#267]
## The icon I want is:

* Name: Ruby
* URL: https://www.ruby-lang.org
* Link to icon: https://cache.ruby-lang.org/pub/misc/logo/ruby-logo-kit.zip and https://www.ruby-lang.org/en/about/logo/

**Comment by wuxmedia** [comment]
Wowsers. This is not an easy one...

**Comment by jmb** [comment]
Had a quick look... If you take the PDF and import into Inkscape, then run through svgo it comes down to just under 9Kb! Probably needs a fair bit of simplification from there. I'll pass for now!

**Comment by wuxmedia** [comment]
I got it down to 5k ish in inkscape by reusing gradients and solid block filling the other facets of the ruby, but the saved svg wasn't correct.

**Comment by wuxmedia** [comment]
Ok found the svg editor on inkscape, that helps to ID the panels and remove change the colour info

**Comment by jmb** [comment]
These tools can help, especially if you use svgo as well to strip all the Inkscape guff out first:
http://petercollingridge.appspot.com/svg-transforms
https://lean-svg.netlify.com/

**Comment by wuxmedia** [comment]
got it down to 1470 only way to take it under is to lose the gradient...
``<svg
xmlns="http://www.w3.org/2000/svg"
aria-label="Ruby" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%" fill="#fff"/><linearGradient id="a" x1="0" x2="1" y1="0" y2="0"><stop offset="0" stop-color="#fff"/><stop offset=".13" stop-color="#e4714e"/><stop offset="1" stop-color="#a80d00"/></linearGradient><path d="M150 415l257-17 19-259-78 158L151 415z" fill="#a00403"/><path d="M326 324l82 73L387 245l-59 79z" fill="#891102"/><path d="M103 301l49 117 40-135-90 20z" fill="url(#a)"/><path d="M183 279l145 46-37-146z" fill="url(#a)"/><path d="M291 189l130-8-100-83-28 93z" fill="url(#a)"/><path d="M277 68l96.9.3-59 33-37.0-33z" fill="url(#a)"/><path d="M85 246l-4 99 24-45z" fill="#b11205"/><path d="M83 245l20 57 88-20 101-93 28-90-44-31-76 28c-24 22-70 66-72 67-1.6.8-31 56-44 82z" fill="#fff"/><path d="M154 141c52-51 119-82 144-56 26 26-1 89-53 140-52 51-118 83-144 57-25-25.89.7-90 52-142z" fill="url(#a)"/><path d="M152 415l40-133 133 43c-48 45-102 83-174 90z" fill="#9f0d02"/><path d="M292 188l34 136c40-42 76-88 94-144z" fill="#871008"/><path d="M421 181c13-41 16-101-48-112l-53 29z" fill="#aa1401"/><path d="M80 345c2 68 51 69 72 70l-48-113z" fill="#9e1209"/><path d="M292 188c31 19 93 57 94 58 2 1 27-42 32-66z" fill="#9f0d02"/><path d="M192 281l54 104c32-17 57-38 79-61z" fill="#900e04"/><path d="M103 302l-8 91c14 20 34 21 55 20-15-37-45-112-47-111z" fill="#8b1104"/><path d="M320 98l107 15c-6-24-23-40-53-45z" fill="#aa1401"/></svg>

**Comment by wuxmedia** [comment]
actually it only gets down to  1286b

**Comment by alexanderadam** [comment]
Maybe some of the gradients aren't necessarily needed. I guess the icon will be recognized even if there are gradients missing.

**Comment by wuxmedia** [comment]
yeah that was 1286 without the (single) gradient.

**Comment by wuxmedia** [comment]
```
<svg
xmlns="http://www.w3.org/2000/svg"
aria-label="Ruby" role="img"
viewBox="0 0 512 512"><rect
width="512" height="512"
rx="15%" fill="#fff"/><path d="M150 415l257-17 19-259-78 158L151 415z" fill="#a00403"/><path d="M326 324l82 73L387 245l-59 79z" fill="#891102"/><path d="M103 301l49 117 40-135-90 20z" fill="#b11205"/><path d="M183 279l145 46-37-146z" fill="#b11205"/><path d="M291 189l130-8-100-83-28 93z" fill="#b11205"/><path d="M277 68l96.9.3-59 33-37.0-33z" fill="#b11205"/><path d="M85 246l-4 99 24-45z" fill="#b11205"/><path d="M83 245l20 57 88-20 101-93 28-90-44-31-76 28c-24 22-70 66-72 67-1.6.8-31 56-44 82z" fill="#fff"/><path d="M154 141c52-51 119-82 144-56 26 26-1 89-53 140-52 51-118 83-144 57-25-25.89.7-90 52-142z" fill="#b11205"/><path d="M152 415l40-133 133 43c-48 45-102 83-174 90z" fill="#9f0d02"/><path d="M292 188l34 136c40-42 76-88 94-144z" fill="#871008"/><path d="M421 181c13-41 16-101-48-112l-53 29z" fill="#aa1401"/><path d="M80 345c2 68 51 69 72 70l-48-113z" fill="#9e1209"/><path d="M292 188c31 19 93 57 94 58 2 1 27-42 32-66z" fill="#9f0d02"/><path d="M192 281l54 104c32-17 57-38 79-61z" fill="#900e04"/><path d="M103 302l-8 91c14 20 34 21 55 20-15-37-45-112-47-111z" fill="#8b1104"/><path d="M320 98l107 15c-6-24-23-40-53-45z" fill="#aa1401"/></svg>

```

**Comment by wuxmedia** [comment]
can gain 30b by going RGB rather than RRGGBB :D

**Comment by alexanderadam** [comment]
ah okay, I see. :wink:

I'm not sure whether it's helpful but this is now 1236b.

```xml
<svg aria-label="Ruby" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><rect width="512" height="512" rx="15%" fill="#fff"/><path d="M407.7 397.3l20.86-257.7L348.02 297l-196 118c80.86-5.675 171.2-11.87 255.7-17.66z" fill="#a00403"/><g fill="#b11205"><path d="M291 189l130-8-101-83-27 93zm-108 90.17L328 325l-37-146zM103.05 301c43.65 139.7 55.22 169 89-19l-90 21zM276 68l97 1-53 29c-10.75-7.227-35.61-24.35-44-30z"/><path d="M85 246l-4 99 23-43z"/></g><path d="M103 302c1.74 1.537 59.67-13.33 89-20l101.3-93.58L319.96 99l-44-31-76 28c-24 22-70 66-72 67-1.6.8-31 56-44 82 3.751 15.96 12.74 39.17 19 57z" fill="#fff"/><path d="M298 85c26 26-1 89-53 140s-118 83-144 57c-25-25.89.7-90 52.85-141s119.2-82 144.2-56z" fill="#b11205"/><path d="M192 282l133 43c-48 45-137.5 86.5-173 90z" fill="#9f0d02"/><path d="M292 188l34 136c40-42 76-88 94-144zm115.7 209.3L387.02 245l-60 79z" fill="#891102"/><path d="M421 181c13-41 16-101-48-112l-53 29z" fill="#aa1401"/><path d="M81 345c2 68 50 69 71 70l-49-113z" fill="#9e1209"/><path d="M292 188c31 19 93 57 94 58 2 1 27-42 32-66z" fill="#9f0d02"/><path d="M192 282l54 103c32-17 57-38 79-61z" fill="#900e04"/><path d="M103 302l-8 91c14 20 34 21 55 20-15-37-45-112-47-111z" fill="#8b1104"/></svg>
```

**Comment by wuxmedia** [comment]
I imagine we'd have to remove a bunch of panels and have one with single colour.
Your one looks a lot nicer though :)
OK 
I ripped a few bits out...
```
<svg aria-label="Ruby" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg"><rect width="512" height="512" rx="15%" fill="#fff"/><path d="M407.7 397.3l20.86-257.7L348.02 297l-196 118c80.86-5.675 171.2-11.87 255.7-17.66z" fill="#a00403"/><g fill="#b11205"><path d="M291,189 421,181 320,98 293,191 Z M 192,282 328,325 293,191 Z m -89,19 c 44,139 55,169 89,-19 l -90,21 z M 276,68 373,69 320,98 C 309,91 284,74 276,68 Z"/><path d="M85 246l-4 99 23-43z"/></g><path d="M298 85c26 26-1 89-53 140s-118 83-144 57c-25-25.89.7-90 52.85-141s119.2-82 144.2-56z" fill="#b11205"/><path d="M192 282l133 43c-48 45-137.5 86.5-173 90z" fill="#9f0d02"/><path d="M292 188l34 136c40-42 76-88 94-144zm115.7 209.3L387.02 245l-60 79z" fill="#891102"/><path d="M421 181c13-41 16-101-48-112l-53 29z" fill="#aa1401"/><path d="M81 345c2 68 50 69 71 70l-49-113z" fill="#9e1209"/><path d="M192 282l54 103c32-17 57-38 79-61z" fill="#900e04"/><path d="M103 302l-8 91c14 20 34 21 55 20-15-37-45-112-47-111z" fill="#8b1104"/></svg>
```

**Comment by wuxmedia** [comment]
**1003** :D

**Comment by jmb** [comment]
Looking good - I think there are a few paths you could combine. Looking at the paths where the colours are the same, you can combine them if the d attribute starts with M (meaning Move to). You don't need the grouping then either!

**Comment by alexanderadam** [comment]
> Your one looks a lot nicer though :)

some points somehow had the wrong position in your variant :wink: 

> Down to 924b now

I don't know how to put this… oh maybe like this:

**U-N-B-E-L-I-E-V-A-B-L-E!!!** it's really amazing what some contributors like you achieve!

**Comment by wuxmedia** [comment]
> wrong position
Yeah I think that was rather aggressive rounding up (or down) on my part. 
There is a PR waiting, gets all complex once there are more that two major commits in the pipe :D

**Comment by alexanderadam** [comment]
But if you create the PR now, @edent might give some feedback already.
Just kidding, no pressure. :wink:

**Comment by positive-tdh** [comment]
I guess. Why not? making up PR now.

**Comment by wuxmedia** [comment]
oops wrong user. erm Nevermind I had it down under 1k but somehow didn't save it.

**Comment by alexanderadam** [comment]
Oh, does this still mean that you will be manage to make a PR for Ruby or rather not?

**Comment by wuxmedia** [comment]
Ii'm not sure the ruby icon looks all that good. 
Also one PR at a time seems to work best. 
I might get some time to edit it back, I don't want to fanny around doing a PR to have it rejected due to too aggressive tweaking.

Let me know if you think it's worth it -- this is flat:
` <svg xmlns="http://www.w3.org/2000/svg" aria-label="Ruby" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#fff"/><path d="M407.7 397.3l20.86-257.7L348.02 297l-196 118c80.86-5.675 171.2-11.87 255.7-17.66z" fill="#a00403"/><path d="M423.39 178.977L320 98l-27 93c109.797 9.317 91.763-9.646 130.39-12.023zM192 282l136 43-35-134zm-89 19c44 139 55 169 89-19l-90 21zM276 68l97 1-53 29c-11-7-36-24-44-30z M85 246l-4 99 23-43z M298 85c26 26-1 89-53 140s-118 83-144 57c-25-25.89.7-90 52.85-141s119.2-82 144.2-56z" fill="#b11205"/><path d="M192 282l133 43c-48 45-137.5 86.5-173 90z" fill="#9f0d02"/><path d="M293 191l33 133c40-42 76-88 94-144zm114.7 206.3L387.02 245 326 324z" fill="#891102"/><path d="M421 181c13-41 16-101-48-112l-53 29z" fill="#aa1401"/><path d="M81 345c2 68 50 69 71 70l-49-113z" fill="#9e1209"/><path d="M192 282l54 103c32-17 57-38 79-61z" fill="#900e04"/><path d="M103 302l-8 91c14 20 34 21 55 20-15-37-45-112-47-111z" fill="#8b1104"/></svg>`

not sure if there is enough space to put a grad in there, I don't think so

**Comment by alexanderadam** [comment]
> Let me know if you think it's worth it -- this is flat:

it looks perfect to me :+1: 
![ruby](https://user-images.githubusercontent.com/372620/67924310-9985a800-fbb0-11e9-869d-348b728e7443.png)

**Comment by romain-dartigues** [comment]
Bravo @wuxmedia :^)
