### ISSUE TITLE
Ubuntu, Archlinux, Linux, Windows and Android should be in the same group

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#268]
All of them represent Operating Systems (or the kernel of it in the case of GNU/Linux).

So they should be semantically grouped together. And you _could_ probably add Apple to it as well. Although I'm  not sure about because it matches good with intel and IBM.

**Comment by romain-dartigues** [comment]
I agree, except for the Apple logo which should be with other "brands"; there is a [logo for MacOS](https://developer.apple.com/softwarelicensing/mac-logo/).

**Comment by edent** [comment]
Agreed. Feel free to make the changes @alexanderadam
