### ISSUE TITLE
Add iHeartRadio Logo

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#282]
## The icon I want is:

* Name: iHeartRadio
* URL: https://www.iheart.com/
* Link to icon: https://images.squarespace-cdn.com/content/v1/54becebee4b05d09416fe7e4/1475621488473-GG13ZAH35UK8B4AQ7IG6/ke17ZwdGBToddI8pDm48kPatQlumu_Sh_yEKNNtje2NZw-zPPgdn4jUwVcJE1ZvWhcwhEtWJXoshNdA9f1qD7aXK0t8ahyzoOLFEHArbPTIvsJ8ZBSuac1iGVlJVssK0Dume1Xhlc5QUWr24itNJvQ/iHM_primary_Color.jpg?format=300w

* Vector version of the logo:
* Official style guide or brand guide: https://brand.iheart.com/

**Comment by Sravanksk** [comment]
Can I work on this @edent

**Comment by SoldierCorp** [comment]
Hi, this task is only add the logo to the `images` folder by following the `CONTRIBUTING.md` ?

**Comment by romain-dartigues** [comment]
fixed in #306.
