### ISSUE TITLE
add XMPP/Jabber

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#295]
## The icon I want is:

* Name: XMPP/Jabber
* URL: https://xmpp.org/
* Link to icon: https://xmpp.org/theme/images/xmpp-logo.svg or https://commons.wikimedia.org/wiki/File:XMPP_logo.svg
* Official style guide or brand guide: https://xmpp.org/about/xsf/jabber-trademark/usage-guidelines

**Comment by wuxmedia** [comment]
I got a tiny one by stripping the gradients out of it. Otherwise I need to learn inkscape to make the objects one and apply one gradient to the shape - I can see the gradient is sort of in there twice.

**Comment by wuxmedia** [comment]
ok well, this is kinda fun. scraping the bytes off one by one :D
down to 1114 bytes ...

**Comment by edent** [comment]
Good fun, isn't it? :-) Take a look at some of the other icons we have here for inspiration. Or post what you've got so far.

**Comment by wuxmedia** [comment]
ok I am doing the maths by hand. :D

**Comment by wuxmedia** [comment]
This has been accepted into the repo now

**Comment by alexanderadam** [comment]
[awesome! Thank you!](https://github.com/edent/SuperTinyIcons/pull/315)
