### ISSUE TITLE
Add Auth0

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#297]
## The icon I want is:

* Name: Auth0
* URL: https://auth0.com/
* Link to icon: https://cdn.auth0.com/styleguide/components/1.0.8/media/logos/img/badge.svg

* Vector version of the logo: https://styleguide.auth0.com/resources/logos
* Official style guide or brand guide: https://styleguide.auth0.com/

Note! Please follow the Contributing Guidelines https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Comment by hirakJS** [comment]
I've raised a PR. Please have a look.

**Comment by edent** [comment]
Please see the comments on that PR.

**Comment by hirakJS** [comment]
I've done the changes you asked for. Please have a look.
