### ISSUE TITLE
add HAML

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#307]
## The icon I want is:

* Name: HAML
* URL: http://haml.info/
* Link to icon: https://github.com/haml/haml/issues/819#issuecomment-66153259 / http://cl.ly/0H0B3V2B3G3Q

**Comment by breadsanta** [comment]
Leave it to me!

**Comment by jmb** [comment]
I had a look at this and I think it might be too complicated a logo! The best I can get it down to from simplifying the SVG given is 10494 bytes!

**Comment by edent** [comment]
Let's keep it open for now. @jmb - please can you post what you've got so far? I can see if I can shrink it any further.

**Comment by jmb** [comment]
Down to 3.75Kb now after removing a lot of unnecessary nodes on the path. Not sure what else can be done...

**Comment by jmb** [comment]
Down to 2363 bytes...

Are there any examples of a simplified version of the logo?

**Comment by edent** [comment]
They have a favicon, but it is so small as to be useless. Grrr!

**Comment by alexanderadam** [comment]
Woah, @jmb from `10494` down to `2363` is stunning!
I'm not a SVG geek but I took your work, cheated a lot and now it's down to `1430`.

Maybe you can use in your PR and tweak it (I had to zip it because GitHub doesn't allow attach SVGs)?

[small_haml_icon.zip](https://github.com/edent/SuperTinyIcons/files/3754303/small_haml_icon.zip)

**Comment by jmb** [comment]
I've removed some more nodes and made a few minor compromises with the design, but hardly noticeable. Down to 1856 bytes now!

**Comment by jmb** [comment]
Wow, nice one @alexanderadam - here is the difference between mine (grey) and yours (red):
<img width="300" alt="haml" src="https://user-images.githubusercontent.com/110238/67268046-702b9480-f4ab-11e9-9406-44629cbfcbbb.png">

Your version comes in at 1443 bytes or thereabouts.

**Comment by jmb** [comment]
And side-by-side:
<img width="125" alt="haml_aa" src="https://user-images.githubusercontent.com/110238/67268251-e4663800-f4ab-11e9-9dfe-5003d21a08d2.png"><img width="125" alt="haml_jmb" src="https://user-images.githubusercontent.com/110238/67268257-e8925580-f4ab-11e9-9b22-429fa1e491d3.png">

**Comment by wuxmedia** [comment]
i gave up after 3k - sterling work here

**Comment by romain-dartigues** [comment]
Please review #340 / https://github.com/edent/SuperTinyIcons/blob/d78486d5226081a4fe52f412fec0229de050e4c9/images/svg/haml.svg

**Comment by jmb** [comment]
That's an interesting take on it @romain-dartigues - I'm not sure if using the background is "allowed" - @edent ? 
You also probably don't need the stroke & stroke-width on the rect.

**Comment by romain-dartigues** [comment]
> That's an interesting take on it @romain-dartigues - I'm not sure if using the background is "allowed"

Why? There are many icons with a background color (acast, Amazon, AirBNB, ...).

> You also probably don't need the stroke & stroke-width on the rect.

I agree, I'm unsure about that and edent will have to choose; it would be the first and I'm not confortable to create a precedent.
However it is how their [favicon](http://haml.info/images/favicon.ico) is.

I could replace the rectangle border by a "shadow" under the "Y" (still as the favicon but would increase a bit the icon size).
