### ISSUE TITLE
Add democracy symbol

### ISSUE THREAD

**Issue by kevinmarks** [edent/SuperTinyIcons#317]
## The icon I want is:

* Name: Democracy Symbol 
* URL: https://democracysymbol.org
* Link to icon:  https://democracysymbol.org/democracy-symbol-white.png

* Vector version of the logo:
```
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
	 width="2160" height="2160" viewBox="0 0 2160 2160">
	<circle cx="1080" cy="1080" r="853" fill="white" stroke="black" stroke-width="150" />
	<rect x="605" y="605" width="950" height="950" fill="none" stroke="black" stroke-width="150"/>
    <text x="910" y="1565" textLength="320" lengthAdjust="spacingAndGlyphs" font-family="sans-serif" font-weight="600" font-size="36" fill="white">democracysymbol.org</text>
</svg>

```
* Note: This is small enough, but I'm not quite sure how to mung the circle radius to make it still touch the square at 512px wide.

**Comment by edent** [comment]
Is it used anywhere? I can't see any references to it online.

**Comment by kevinmarks** [comment]
It's pretty new, but likely to be more visible after the march this
weekend.

**Comment by alexanderadam** [comment]
> It's pretty new

It seems so.

[This symbol doesn't seem to be relevant for a search engine](https://duckduckgo.com/?q=democracy+symbol&t=h_&iax=images&ia=images). And, you know, most search engines are kind of working democratically and people are 'voting' with their surfing behaviour and decide what's relevant to them.

Also there are also a few (old) democracy symbols around.
For instance the people back then in the state of Athens (you know, the people who invented the term democracy) had a symbol for it.
And there's also 'Wo Nsa Da Mu A' an African symbol that also has the meaning of democracy in it. I can find both symbols by searching for `democracy symbol` in a search engine but yours doesn't appear at all.
It's also [not relevant enough that someone considered added it to the democracy Wikipedia page](https://en.wikipedia.org/wiki/Democracy) either.

So I somehow have the feeling that that the symbol you are mentioning here is probably not a international and general democracy symbol, right?

**PS:** I'm not related to the project `SuperTinyIcons`. I'm just curious about whether this symbol really represents democracy for an adequate amount of people in the world.
