### ISSUE TITLE
Alphabetical list - a script helper

### ISSUE THREAD

**Issue by jmb** [edent/SuperTinyIcons#342]
I'm not sure if this is useful or not, but a wrote a python3 script to generate a full alphabetical listing. I've started to make it configurable but haven't added any arguments or anything yet - any thoughts?

Output:
https://github.com/jmb/SuperTinyIcons/blob/scripts/ALL.md

Script:
https://github.com/jmb/SuperTinyIcons/blob/scripts/scripts/list_all.py

(Edit: fixed links after breaking them with my fumbling around git!)

**Comment by edent** [comment]
Looks interesting.

1. Probably best to use a case-insensitive sort. Otherwise things like `eBay` appear at the end of the list.
2. The sizes go a bit weird when the title text is too long. That's a problem on my main index as well. Not sure what the fix is.

**Comment by jmb** [comment]
Thanks, it was a quick hack. I wonder if some inline CSS (maybe not allowed in .md?) or putting titles in separate cells might fix it?

**Comment by jmb** [comment]
I had a refactor and have made a page which creates the inverse of the icon if it only has 2 colours (well tries too!). At the moment it outputs HTML with inline svgs (which breaks some as well) rather than files, but I'll probably make a version to generate files soon.

It's interesting in places as it possibly shows some icons that could be re-factored to reduce in size and improved to make an inverse possible.

Not sure where to take this next!

**Comment by edent** [comment]
Nice. Might be an idea to have a page which show the filled in and inverse icons. I know some people want them like that.

**Comment by jmb** [comment]
Here's a first go:

https://github.com/jmb/SuperTinyIcons/blob/scripts/INVERTED.md

See the scripts directory in that branch for the code. It's somewhat quick and dirty!

**Comment by edent** [comment]
Thanks for this, I've finally integrated something like it to help regenerate the README.
