### ISSUE TITLE
New Firefox Logo

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#344]
## The icon I want is:

* Name: Firefox
* URL: https://mozilla.design/firefox/logos-usage/

* Vector version of the logo: https://mozilla.design/files/2019/10/Firefox-Browser-Logo-Assets.zip

Note, @judeGibbons did amazing work on the old one :-)

**Comment by judeGibbons** [comment]
I'm working on it! Also on the new Edge one...
