### ISSUE TITLE
Fix Rust

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#348]
The Rust icon has a problem.

Some rendering engines require XLINK to be in the form `xmlns:xlink="http://www.w3.org/1999/xlink"`

The Rust icon uses `xmlns:x="http://www.w3.org/1999/xlink"`

If we convert to proper XLINK syntax, the files is 1,053 bytes - that's too large.

Otherwise, it looks like this:
![Screenshot at 2019-10-26 17-43-56](https://user-images.githubusercontent.com/837136/67623021-3abed800-f818-11e9-8443-69b494cb6ec5.png)

**Comment by romain-dartigues** [comment]
Well, it look like a crowned R :^D.
I prefer fixing the redering engine than the Rust logo, a wonderful job was made on this icon...

More seriously, it would be nice to have an informative checklist of sofwares/versions the logo *must* render correctly (ie: chrome 70+, firefox 64+, firefox mobile 68+, etc.).

For example, software using `libpixbufloader-svg` (geeqie, nemo, ...) fail miserably to render andOTP, elementaryos, gojek, grafana, haml, keybase, redhat, rust, sentry, tutanota, wekan.

**Comment by judeGibbons** [comment]
I remember this issue and there was a decision make to move from using xlink: to x: ([here](https://github.com/edent/SuperTinyIcons/issues/184#issuecomment-473293345)) but I see that later the problems were flagged with doing it this way. Happy to look at redoing mine, if I can...
