### ISSUE TITLE
Add general chat icon

### ISSUE THREAD

**Issue by kokarn** [edent/SuperTinyIcons#36]
Really nice project! Looking forward to using it.

Something that I'm currently missing is something that could be used as an icon for a forum, general discussion, chat or something like that.

Something like the one [font awesome uses](http://fontawesome.io/icon/comments/) or something like [this](https://www.iconfinder.com/icons/206461/chat_keynote_messages_icon) with a background would be pretty useful.

**Comment by edent** [comment]
Looks good! Please send a pull request.

**Comment by kokarn** [comment]
I'm horrible with anything that isn't code I'm afraid.
I'll see if I can find somebody to help me tho, but no high hopes :/

**Comment by edent** [comment]
@kokarn my friend, SVG *is* code. You can do this - I believe in you :-)
