### ISSUE TITLE
add Pixelfed

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#361]
## The icon I want is:

* Name: Pixelfed
* URL: https://pixelfed.org/ / https://github.com/pixelfed/pixelfed
* Link to icon: https://github.com/pixelfed/pixelfed/blob/dev/public/img/pixelfed-icon-color.svg

I have the feeling that this is a touch one. So whoever wants to give it a try: good luck!

**Comment by edent** [comment]
@romain-dartigues shout when you're ready for this.

**Comment by romain-dartigues** [comment]
Sorry, I've been AFK for a while and I'm a bit short on time to finish my experiments on Pixelfed (I had fun trying till now though).

If someone want to give it a try, feel free; otherwise I'll try to complete it in a few weeks.
