### ISSUE TITLE
Add cryptocurrency-related icons

### ISSUE THREAD

**Issue by samthelion17** [edent/SuperTinyIcons#362]
## The icon I want is: Blockchain Wallet

* Name: Blockchain Wallet
* URL: https://www.blockchain.com/
* Link to icon: https://cdn.freebiesupply.com/logos/large/2x/blockchain-logo-svg-vector.svg

* Vector version of the logo: https://cdn.freebiesupply.com/logos/large/2x/blockchain-logo-svg-vector.svg
* Official style guide or brand guide: 

## The icon I want is: Coinpot

* Name: Coinpot
* URL: https://coinpot.co
* Link to icon: http://www.bitcoins4free.ml/wp-content/uploads/2017/12/logo-1.png

* Vector version of the logo:
* Official style guide or brand guide: 

## The icon I want is: Humble Bundle

* Name: Humble Bundle
* URL: https://www.humblebundle.com/
* Link to icon: 

* Vector version of the logo: https://cdn.worldvectorlogo.com/logos/humblebundle.svg
* Official style guide or brand guide:

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by Sharps** [comment]
I thought I'd give this a shot for the hacktoberfest thing, made the blockchain wallet icon and then noticed that their logo is now different, heh. Still ended up with 557 bytes even though it looks very simple. No idea how you could fit the mess that is the coinpot logo into 1024 bytes.

I had fun though, when it comes to vectors for me everything would end with clicking save on illustrator, never really looked into the code before.

In any case, could you check if the one I made stands up to your standards ? Thanks
https://www.dropbox.com/s/s9m9rqciizqwc7p/blockchain.svg?dl=0

**Comment by edent** [comment]
@Sharps that looks really good. Could you make one for the updated wallet? Make sure it follows the template in the CONTRIBUTING file and I'll happily accept a pull request.
