### ISSUE TITLE
add Fritz!

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#363]
## The icon I want is:

* Name: Fritz!
* URL: https://sso.myfritz.net/ / https://en.avm.de/
* Link to icon: https://en.wikipedia.org/wiki/Fritz!Box#/media/File:Fritz!.svg

Sorry but I guess this is again a very difficult one.

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by logiclrd** [comment]
May be doable if the background is converted to the standard rounded corners of the template.
