### ISSUE TITLE
Validate SVGs

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#365]
Using https://validator.w3.org/check shows some errors in SVGs.

For example https://github.com/edent/SuperTinyIcons/blob/master/images/svg/itunes_podcasts.svg

> Element stop is missing required attribute offset.

Doesn't affect rendering, as far as I can tell. But might be worth checking all of them.

**Comment by romain-dartigues** [comment]
Should it be part of a meta-task (GitHub project?) about continuous integration?
Some checks would be informational (like the SVG validation against the W3C standards), other would be critical (file size, missing reference, ...).

**Comment by jonatjano** [comment]
I started working on this one (didn't push it yet),
I tested for size and W3C validation, there are 8 validation failures, gonna fix these before creating a pull request (likely tonight).

I did the tests with [mocha](https://mochajs.org/) + [chai](https://www.chaijs.com/) and installed [node-fetch](https://www.npmjs.com/package/node-fetch) for easiness (all as devDependencies), tell me if you prefer another framework.
