### ISSUE TITLE
Add Gatehub.net

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#367]
## The icon I want is:

* Name: GateHub
* URL: https://gatehub.net/
* Link to icon: https://gatehub.net/resources/ico/gatehub-152.png https://gatehub.net/blog/content/images/2019/04/icon-logo-black@3x_o-1-1.png 

* Vector version of the logo: https://seeklogo.com/vector-logo/323348/gatehub
* Official style guide or brand guide:

**Comment by alexanderadam** [comment]
I guess [you can close this now](https://github.com/edent/SuperTinyIcons/commit/6cb62d2c9ef422fab47067bd888259ba02057cff)? :wink:

**Comment by romain-dartigues** [comment]
Woops, seems 6cb62d2 erroneously referred to #366...
