### ISSUE TITLE
Add TeamSpeak

### ISSUE THREAD

**Issue by thhan** [edent/SuperTinyIcons#368]
## The icon I want is:
* Name: TeamSpeak
* URL: https://www.teamspeak.com/
* Link to icon: https://www.teamspeak.com/downloads/media-pack/png/ts-stacked-blueblack.zip
* Official style guide or brand guide: https://www.teamspeak.com/en/more/media-pack/

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).
