### ISSUE TITLE
Add Uplay

### ISSUE THREAD

**Issue by jhasse** [edent/SuperTinyIcons#371]
## The icon I want is:

* Name: Uplay
* URL: https://uplay.ubisoft.com
* Link to icon: https://icon-library.net/icon/uplay-icon-8.html

* Vector version of the logo: I haven't found one yet.
* Official style guide or brand guide: Don't know if that even exists.

**Comment by The24thDS** [comment]
Is this issue resolved?

**Comment by edent** [comment]
It is, good spot!
