### ISSUE TITLE
add KeePassDX

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#374]
## The icon I want is:

* Name: KeePassDX
* URL: https://www.keepassdx.com/ / https://github.com/Kunzisoft/KeePassDX
* Link to icon: https://github.com/Kunzisoft/KeePassDX/blob/master/art/ic_launcher.svg

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).
