### ISSUE TITLE
Add Friendica

### ISSUE THREAD

**Issue by nupplaphil** [edent/SuperTinyIcons#376]
* Name: Friendica
* URL: https://friendi.ca
* Link to icon: https://github.com/friendica/docker/blob/master/friendica.svg

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by logiclrd** [comment]
I'll give this one a go. :-)
