### ISSUE TITLE
Angel List

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#381]
## The icon I want is:

* Name: Angel List
* URL: https://angel.co/
* Link to icon: https://angel.co/webpack/64bfdcefe79bd40c1c90e9096fd76255.svg

* Vector version of the logo: https://angel.co/webpack/64bfdcefe79bd40c1c90e9096fd76255.svg
* Official style guide or brand guide:

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by azhsetiawan** [comment]
Hi @edent 
I've read guidelines and workin on this
