### ISSUE TITLE
Preact

### ISSUE THREAD

**Issue by jhpratt** [edent/SuperTinyIcons#415]
## The icon I want is:

* Name: Preact
* URL: https://preactjs.com
* Link to icon: https://raw.githubusercontent.com/preactjs/preact/8b0bcc927995c188eca83cba30fbc83491cc0b2f/logo.svg

* Vector version of the logo: ^^
* Official style guide or brand guide: None that I can find

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by brunocerecetto** [comment]
Hi! assign it to me!
