### ISSUE TITLE
Cargo/crates.io

### ISSUE THREAD

**Issue by jhpratt** [edent/SuperTinyIcons#416]
## The icon I want is:

* Name: crates.io
* URL: crates.io
* Link to icon: https://www.rust-lang.org/logos/cargo.png

* Vector version of the logo: None that I can find
* Official style guide or brand guide: https://www.rust-lang.org/policies/media-guide

**Comment by edent** [comment]
That's almost certainly too complicated to shrink down.

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).
