### ISSUE TITLE
add WireGuard VPN

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#419]
## The icon I want is:

* Name: WireGuard VPN
* URL: https://www.wireguard.com/
* Link to icon: https://www.wireguard.com/img/wireguard.svg
* Official style guide or brand guide: https://www.wireguard.com/trademark-policy/ (`The color of the logo is RGB #88171a`)

**Comment by edent** [comment]
That looks really complex. I think we'll struggle to get it down to 1,023 bytes.

**Comment by alexanderadam** [comment]
I can imagine that. [There's a smaller version on the website (i.e. for the favicon and touch icons)](https://www.wireguard.com/img/icons/apple-touch-icon-76.png). Maybe that's a bit more realistic?
![apple-touch-icon-76](https://user-images.githubusercontent.com/372620/84000417-e0b4f200-a964-11ea-9efc-849b6a88fe54.png)

**Comment by logiclrd** [comment]
I've had a go at this one, after seeing that 17jiangz1's PR from June had blocking issues.

**Comment by edent** [comment]
Closed in #455
