### ISSUE TITLE
add Samsung

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#420]
this is probably a difficult one because I didn't found a proper circular one. But maybe the "S" could be used for that (like in [Samsung's favicon](https://cdn.samsung.com/etc/designs/smg/global/imgs/favicon.ico)? Otherwise [their app icon is the type in the Samsung blue](https://www.samsung.com/etc/designs/smg/global/imgs/app_ico.png).

## The icon I want is:
* Name: Samsung
* URL: https://www.samsung.com/
* Link to icon: https://en.wikipedia.org/wiki/File:Samsung_Logo.svg

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).

**Comment by logiclrd** [comment]
I'll give this one a go.
