### ISSUE TITLE
Add Kaggle

### ISSUE THREAD

**Issue by mahirahamzah** [edent/SuperTinyIcons#427]
## The icon I want is: Kaggle

* Name: Kaggle
* URL: https://www.kaggle.com/
* Link to icon: https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/189_Kaggle_logo_logos-512.png

* Vector version of the logo: https://storage.googleapis.com/kaggle-competitions/kaggle/3136/media/kaggle-transparent.svg
* Official style guide or brand guide: https://www.kaggle.com/brand-guidelines

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).
