### ISSUE TITLE
Add Roundcube

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#429]
## The icon I want is:

* Name: Roundcube
* URL: https://roundcube.net/
* Link to icon: https://roundcube.net/images/roundcube_logo_icon.svg

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).
