### ISSUE TITLE
Shrink Inner Icons

### ISSUE THREAD

**Issue by joezimjs** [edent/SuperTinyIcons#43]
If you bump the radius to 50% to make the icons circular, some of the icons (linked in, RSS, maybe more) extend beyond the colored circle background.

**Comment by edent** [comment]
Interesting. The icon box is supposed to be 400*400 in a 512*512 wrapper. So what's the maths for the optimal size?

**Comment by RazrFalcon** [comment]
It's a huge change. A lot of icons can't be fit in the circle, so they should be changed/rescaled, which includes making them pixel-perfect again and this takes a lot of time.

**Comment by joezimjs** [comment]
400x400 makes the diagonal dimension 565px, which is larger than the 512px diameter of the circle. If you drop the icon down to 350x350, the diagonal will be 495px which should work well. (Pythagorean theorem for all this stuff) Wouldn't you be able to multiply all dimensions/coordinates by 7/8 to make this work? I might give it a try myself when I get to my PC.

**Comment by edent** [comment]
Would love to see them!

**Comment by joezimjs** [comment]
Nevermind. I forgot how complicated SVG paths are. It'd take me a while just to learn enough to understand how they work. :stuck_out_tongue_closed_eyes:

A potential alternative would be to increase the viewbox and rectangle size to 600 and just reposition everything. Which I actually know enough to do (I think). :smile: How do you guys feel about that?

**Comment by edent** [comment]
Try it. Send a PR and we'll see what it looks like. 

Might be easier just to alter the ones which break the bounds of the circle though.

**Comment by joezimjs** [comment]
Submitted PR #44

**Comment by edent** [comment]
Now tracked in #86
