### ISSUE TITLE
Add Jellyfin

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#430]
* Name: Jellyfin
* URL: https://jellyfin.org/
* Link to icon: https://jellyfin.org/images/banner-dark.svg

**Comment by edent** [comment]
Hey Hacktoberfest participants! If you'd like to tackle this issue, [please follow the simple guidelines](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md).
