### ISSUE TITLE
Add freeCodeCamp

### ISSUE THREAD

**Issue by ronan696** [edent/SuperTinyIcons#449]
## The icon I want is:

* Name: freeCodeCamp
* URL: https://www.freecodecamp.org/
* Link to icon: https://design-style-guide.freecodecamp.org/downloads/fcc_secondary_small.svg

* Vector version of the logo: https://design-style-guide.freecodecamp.org/downloads/fcc_secondary_large.svg
* Official style guide or brand guide: https://design-style-guide.freecodecamp.org/

Would be happy to create a PR for the same :)

**Comment by edent** [comment]
Cool! Do it 😎
