### ISSUE TITLE
Add DataCamp

### ISSUE THREAD

**Issue by Satyam-kumar-yadav** [edent/SuperTinyIcons#451]
## The icon I want is:

* Name: DataCamp
* URL: https://learn.datacamp.com/
* Link to icon: https://waffles.datacamp.com/design/icons

* Vector version of the logo: https://vectorlogoseek.com/wp-content/uploads/2019/05/datacamp-vector-logo.png
* Official style guide or brand guide: https://waffles.datacamp.com/design/icons

Would be happy to create a PR for the same :)

**Comment by edent** [comment]
Please add a PR 😁
