### ISSUE TITLE
New Google Logos!

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#458]
Google is getting some *horrible* new logos. https://techcrunch.com/2020/10/06/googles-new-logos-are-bad/

They are not yet available at https://www.google.com/permissions/trademark/logos-list/

Non-vector logos at https://workspace.google.co.uk/intl/en_uk/

Anyone have a source of the vectors?

**Comment by ronan696** [comment]
@edent, Found the vectors for some of the new logos.

- Gmail: https://www.google.com/gmail/about/static/images/logo-gmail.svg
- Drive: https://kstatic.googleusercontent.com/files/f4b4fbcc6119576da7ab3f68270196009fc1b16f1927910842d793c385115593b6dd5fbe9a1e21fe64f3cbbc509c3a02c95ebc9635f76c355282482986f1fe7d
- Meet: https://apps.google.com/static/img/meet-logo.svg
