### ISSUE TITLE
Add Citrix

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#460]
## The icon I want is:

* Name: Citrix
* URL: https://www.citrix.com
* Link to icon: https://www.citrix.com/en-gb/news/media-resources.html

**Comment by edent** [comment]
Here's there social media icon - https://twitter.com/citrix/photo

**Comment by alexanderadam** [comment]
Isn't this the same as [this](https://www.citrix.com/content/dam/citrix61/en_us/images/logos/citrix/citrix-logo-black.eps) or [this](https://www.citrix.com/content/dam/citrix61/en_us/images/logos/citrix/citrix-logo-reverse.eps) except the circle around it? :thinking:

**Comment by edent** [comment]
Yes. Sorry, that's what I was trying to say.
