### ISSUE TITLE
Add Bitwarden

### ISSUE THREAD

**Issue by alexanderadam** [edent/SuperTinyIcons#466]
## The icon I want is:

* Name: Bitwarden
* URL: https://bitwarden.com/
* Link to icon: https://github.com/bitwarden/brand/tree/master/logos

* Vector version of the logo:
* Official style guide or brand guide:

**Comment by edent** [comment]
We already have Bitwarden https://github.com/edent/SuperTinyIcons/blob/master/images/svg/bitwarden.svg

**Comment by alexanderadam** [comment]
Sorry, my fault!
