### ISSUE TITLE
Add C++ please

### ISSUE THREAD

**Issue by kareldonk** [edent/SuperTinyIcons#472]
Hello, please add the C++ icon. I'm sending it here attached as a zip file; the SVG is optimized to 1023 bytes (you might be able to do better). Original is at https://isocpp.org/

[cplusplus.zip](https://github.com/edent/SuperTinyIcons/files/5497529/cplusplus.zip)

**Comment by edent** [comment]
Thanks! Would you like to submit it as a PR? That way people can see it was you who contributed.
If not, let me know and I'll add it myself.

**Comment by kareldonk** [comment]
You can add it yourself, no problem :)
