### ISSUE TITLE
1Password logo

### ISSUE THREAD

**Issue by TheChilliPL** [edent/SuperTinyIcons#476]
## The icon I want is:

* Name: 1Password
* URL: [1password.com](https://1password.com/)
* Link to icon: [here][svg]

* Vector version of the logo: [same as above][svg] (4673 bytes)
* Official style guide or brand guide: [Press kit & brand assets | 1Password](https://1password.com/press/)

![1Password logo](https://user-images.githubusercontent.com/18823939/98411835-0f033e80-2077-11eb-8742-fe0ca6cf511d.png)

[svg]: https://1password.com/img/press/logo.e5bf08b08157e08a1b9112fcd58a54b6.svg

**Comment by btrem** [comment]
I'm working on this, but I don't know if I can pull it off. There are 8 different rings. Using fills and strokes, I've accomplished that with 5 `<circle>` elements. But then there's the keyhole. It's med/dark blue, with a dark blue border, and a second white border outside that. I need to either create two almost identical paths, or define a path in a `<defs>` element, and then reference it twice, using transform scale. So far, it's not quite right, and I'm near or over 1kb depending on how I do it. And I haven't even started on the shadows between the 2 outer rings.

**Comment by edent** [comment]
I believe in you.

**Comment by edent** [comment]
Post what you've go so far, and we can all try to help.

**Comment by btrem** [comment]
> I believe in you.

(:

https://github.com/btrem/SuperTinyIcons/blob/1password/images/svg/1password.svg

To maintain readability, I did not collapse whitespace.

**Comment by edent** [comment]
That's looking really good!

**Comment by TheChilliPL** [comment]
It's already looking good, but this white rounded square background isn't a part of this logo, no?

**Comment by btrem** [comment]
The rounded square is part of all the icons in SuperTinyIcons. It is white for colored icons. It is colored where the icon is white.

**Comment by btrem** [comment]
I added the white outline to the keyhole. NB: this is a rough trace. It's at a bit over 900 bytes, but we still have to add the shadows.  :-o

**Comment by TheChilliPL** [comment]
Ohh, okay
I can't find why is that, though—wouldn't it make more sense to just leave them how it is? The user can add the background in CSS, if they're using it on the web, for example

**Comment by btrem** [comment]
You'd have to ask @edent (the owner of this repo). I suspect the idea is someone can copy the source code of any svg icon into a webpage with minimal fuss. Though, to be fair, one would have to set height/width in css, or constrict it in some other way.
