### ISSUE TITLE
Github Dark in Light Logo

### ISSUE THREAD

**Issue by amirghazi87** [edent/SuperTinyIcons#477]
Github Dark in Light Logo

**Comment by edent** [comment]
Thanks @Paptoos - do you have a link to the logo?

**Comment by Paptoos** [comment]
https://github.com/logos 
download mark from this link
then go to png folder and see GitHub-Mark-Light-120px-plus.png
If it is hard , I upload it to a cloud storage
https://mega.nz/file/n4tFWC5K#Ogzh_Zoo34OrCmbu-sQrKSMOsI0wPie_i0v5tF9oWLA
