### ISSUE TITLE
Extra reduction in size

### ISSUE THREAD

**Issue by yatru** [edent/SuperTinyIcons#478]
You can use the (https://yqnn.github.io/svg-path-editor/) to reduce the path size even more (In some cases).
Source code: https://github.com/Yqnn/svg-path-editor/

**Comment by edent** [comment]
Cool! Please let us know how you get on.

**Comment by yatru** [comment]
You only need to go to https://yqnn.github.io/svg-path-editor/ and paste the Path and click on Minify
In some cases it will not help, but in other it will. The source code is available to automate this. 
Also, it's an editor, so you can personalize the logos.

**Comment by edent** [comment]
OK. Which icons need the most work?

**Comment by yatru** [comment]
They are pretty well, but for example twitter could be reduced 19 bytes
"M437 152a72 72 0 01-40 12a72 72 0 0032-40a72 72 0 01-45 17a72 72 0 00-122 65a200 200 0 01-145-74a72 72 0 0022 94a72 72 0 01-32-7a72 72 0 0056 69a72 72 0 01-32 1a72 72 0 0067 50a200 200 0 01-105 29a200 200 0 00309-179a200 200 0 0035-37" 

You should check the source code to automate the possible reduction in some cases

**Comment by yatru** [comment]
Slack only 2 bytes "M149 305a39 39 0 01-78 0c0-22 17 -39 39 -39h39zM168 305a39 39 0 0178 0v97a39 39 0 01-78 0z"

**Comment by edent** [comment]
Thanks. Please send that as a PR.

If you know of a way to automate with GitHub's CI, please let me know.

**Comment by yatru** [comment]
Thanks to you , great collection

**Comment by TPS** [comment]
> Thanks. Please send that as a PR.
> 
> If you know of a way to automate with GitHub's CI, please let me know.

@edent You should subscribe to [Imgbot.Net](httpS://imgbot.net/), which would automatically shrink, commit to `imgbot` branch, & PR most images (not just SVGs).  You'd also probably want to commit an `.imgbotconfig` in your root to make sure to squeeze every bite out of the already tiny SVGs.  I use
````
{
    "compressWiki": "true"
    "minKBReduced": null
}
````
If you wish, I could submit a PR that'd have that `.imgbotconfig` & the 1st round of SVG savings.  Just let me know!

**Comment by edent** [comment]
@TPS we have exhausted the limits of SVGO. That's all imgbot can do for SVGs. While it is great for unoptimised files, it can't do anything for our already optimised files.
If you can find any savings, please do submit them as PRs.

**Comment by TPS** [comment]
> If you can find any savings, please do submit them as PRs.

@edent Please check #482 & tell me what you think. 🙇🏾‍♂️
