### ISSUE TITLE
Add Etsy (You have the E, but not the whole word)

### ISSUE THREAD

**Issue by jonaheschwartz** [edent/SuperTinyIcons#494]
## The icon I want is:

* Name: Etsy 
* URL: https://www.etsy.com/ 
* Link to icon: https://stripydot.com/wp-content/uploads/2019/01/Etsy-app-logo-design-icon.png

* Vector version of the logo: This may work too: 
![image](https://user-images.githubusercontent.com/42906364/99472712-38458980-2917-11eb-93ea-95d07e999fc9.png)

* Official style guide or brand guide:

**Comment by edent** [comment]
Official logos at http://extfiles.etsy.com/Press/etsy-logo.zip
