### ISSUE TITLE
add accessibility guidance

### ISSUE THREAD

**Issue by LJWatson** [edent/SuperTinyIcons#50]
Would it be helpful to provide some short guidance on adding accessibility semantics to the icons (when used within links and/or without)? Happy to suggest something if so.

**Comment by edent** [comment]
Oooh! Yes please. At the moment I'm just using `alt` - but happy to know of better ways.

**Comment by LJWatson** [comment]
It'd be good to add `role="img"` and `aria-label="iconBrand"` to each of the super-tiny SVG files. Then reference this from the readme.md. Will this bust the super-tininess?

The advice on the readme would then be something like:

<The super-tiny icons are accessible by default. Each one has:
* `role="img"`, to inform screen readers that the icon is a graphic
* `aria-label="XYZ"` (where XYZ is the icon's brand name), to give the icon an accessible name

Note: if using the ```<svg>``` elements within an ```<img>``` element, the alt attribute should still be used to give the icon an accessible name because the ARIA is not recognised in this context.<

If this seems like a good approach, I'll get a PR together that adds the ARIA to the super-tiny SVG files, and the above information to the readme.

**Comment by edent** [comment]
Sounds good! Looks like that will add about 40 bytes to each logo. That'll bust the size of a few of them, so we might have to do some fiddling.
