### ISSUE TITLE
Percent sign in rx attribute of rect tags can be omitted

### ISSUE THREAD

**Issue by eloydegen** [edent/SuperTinyIcons#52]
To save a single byte, the `%` can be omitted in the `rx` attribute of `rect` tags. So, `<rect height="512" rx="15%" width="512"/>` would become `<rect height="512" rx="15" width="512"/>`

Tested in Firefox 57 and Ristretto 0.8.2.

Edit: this is incorrect, it will be interpreted as px instead of percent.

**Comment by edent** [comment]
That's a really good idea! When you drop off the `%` the radius is measured in pixels.  512*.15 is about 80px.

**Comment by eloydegen** [comment]
Oh, I didn't considered that, thanks! So, to merge these changes, the values in the corresponding logo's have to be changed and the interactive tool should be changed to use pixel values. I'm looking into this now.

**Comment by edent** [comment]
Cool! Please remember to update the README with the new sizes :-)
