### ISSUE TITLE
mailchimp.svg contains useless m command

### ISSUE THREAD

**Issue by benkasminbullock** [edent/SuperTinyIcons#529]
In path in the the mailchimp.svg icon, there is a z followed by an m followed by a z followed by another m:

zm-58-6zm-73-152c

It doesn't make much sense, this could be a single m command.

**Comment by edent** [comment]
Good spot - please raise a pull request.

**Comment by kpym** [comment]
I have created a pull request #533 (removing this segment and shrinking the colors).
