### ISSUE TITLE
Add Ecosia Icon

### ISSUE THREAD

**Issue by MoPaMo** [edent/SuperTinyIcons#566]
## The icon I want is:

* Name: Ecosia
* URL: https://ecosia.org/ / https://info.ecosia.org/what
* Link to icon: https://upload.wikimedia.org/wikipedia/en/1/11/Ecosia_logo.png / 
https://upload.wikimedia.org/wikipedia/de/d/d8/Ecosia_Logo.png

* Vector version of the logo: https://commons.m.wikimedia.org/wiki/File:Ecosia-like_logo.svg
* Official style guide or brand guide: https://ecosia.co/ecosialogos

**Comment by Kishore-abhimanyu** [comment]
Can you assign me on this?

**Comment by kalpeshT101** [comment]
Would like to work on this.
