### ISSUE TITLE
Incorrect Google icon

### ISSUE THREAD

**Issue by ErikHumphrey** [edent/SuperTinyIcons#57]
I've never seen that Google logo used as a square icon. Yes, it's the G in the full Google logo, but the Google logo used for things like Google's Oauth is similar to the favicon, having four colours in the G. Perhaps there few reasons to use the logo in the first place as there isn't much you can link on Google that doesn't have its own icons, like Blogger, Google Maps, or Google+. But even if my website linked to Google Books or Google Scholar, I would probably use one similar to the official favicon used for Google Search and Google Sign-In.

![Evolving Google Identity](https://storage.googleapis.com/gd-wagtail-prod-assets/original_images/evolving_google_identity_inline_002.gif)

_"The Google G is a compact version of the Google logo that works in small contexts."_  
 https://design.google/library/evolving-google-identity/

The official download for the Google G for use in the icon can be found [here](https://madeby.google.com/static/images/google_g_logo.svg).

**Comment by eloydegen** [comment]
I have just fixed this with #60
