### ISSUE TITLE
Challenge! OpenStreetMap icon

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#575]
## The icon I want is:

* Name: OpenStreetMap
* URL: https://www.openstreetmap.org/
* Link to icon: https://wiki.openstreetmap.org/w/images/7/79/Public-images-osm_logo.svg

There's a set of simplified logos at https://wiki.openstreetmap.org/wiki/Logos#Other_logos which might be easier to shrink.

For example https://wiki.openstreetmap.org/w/images/5/57/Logo_simple_colors.svg

**Comment by Eiim** [comment]
I have a 1021 byte icon based off the OSM Hispanic logo, but I'd like it to look a little nicer:

![OSM_Hispanic_modified4](https://user-images.githubusercontent.com/24627058/133871315-427623ed-6d37-4c86-a7c9-5c10d6108b09.png)

[OSM_Hispanic_modified4.zip](https://github.com/edent/SuperTinyIcons/files/7189136/OSM_Hispanic_modified4.zip)

**Comment by sidverma32** [comment]
@edent  Can i take this task?

**Comment by edent** [comment]
Do it! 😀
