### ISSUE TITLE
Add Filestash Icon

### ISSUE THREAD

**Issue by itzTheMeow** [edent/SuperTinyIcons#583]
## The icon I want is:

* Name: Filestash Logo
* URL: https://www.filestash.app/
* Link to icon: https://downloads.filestash.app/brand/logo_white.svg

* Vector version of the logo: above
* Official style guide or brand guide: #7ec4e7 blue background

**Comment by LaLiLuLeLoPS** [comment]
can i work on this?

**Comment by edent** [comment]
@LaLiLuLeLoPS I think @gunwant11  got there first. Feel free to work on the other icons.

**Comment by Bharadwajshivam28** [comment]
@edent can i work on it not under any event just i want to work on it

**Comment by edent** [comment]
Go for it. Remember to read the contributing guide.

**Comment by Bharadwajshivam28** [comment]
> Go for it. Remember to read the contributing guide.

Okay
