### ISSUE TITLE
Help With Pop!_OS Icon

### ISSUE THREAD

**Issue by ecrax** [edent/SuperTinyIcons#610]
I have already recreated the icon by hand and put it into svgcleaner but I am stuck at 1,248 bytes.
If anyone knows how to make it even smaller feel free to let me know :).

https://pastebin.com/69RK3Nd8

**Comment by baybal** [comment]
```<svg xmlns="http://www.w3.org/2000/svg" aria-label="Pop!_OS" viewBox="0 0 512 512"><rect width="512" height="512" fill="#48b9c7" rx="15%"/><path fill="#fff" d="M144 145c-20 20 12 48 40 112 33 64 47 93 66 83 18-15-13-58-17-87 121-61 5-217-90-107Zm82 72q-11 2-24-27t-8-41q5-12 23 5t19 41q1 24-15 22Zm88-25c-23 133-2 137 50 13 11-25-45-42-50-13Zm-6 120c-15-3-27 22-7 30 19 3 21-25 7-30Zm-141 47a15 15 0 1 0 0 30h175a15 15 0 1 0 0-30Z"/></svg>```

**Comment by ecrax** [comment]
I use chrome as well, strange.
