### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by ace-dent** [edent/SuperTinyIcons#616]
Please consider cutting a release, to have a fixed snapshot of the icons.
As well as the git tag, a fixed URL of all the icons may be useful for derivative projects.

**Comment by benkasminbullock** [comment]
Github does most of the work of automating releases if you try the menu under "Releases" (if owner).

**Comment by colincameron** [comment]
Are there any plans to create a new release, @edent? I'd prefer installing via NPM rather than manually including the icons in my project, but the latest release 0.4.0 is over two years old.

**Comment by edent** [comment]
I've done https://github.com/edent/SuperTinyIcons/releases - is that what you mean?

(Sorry, very jetlagged and catching up on old issues.)

**Comment by Eiim** [comment]
0.5.0 released!
