### ISSUE TITLE
update youtube icon

### ISSUE THREAD

**Issue by wahyu6070** [edent/SuperTinyIcons#628]
## The icon I want is:

* Name: 
* URL: 
* Link to icon: 

* Vector version of the logo:
* Official style guide or brand guide:

**Comment by Eiim** [comment]
I know this is a bit old of an issue, but I don't see how the logo has changed?

**Comment by benkasminbullock** [comment]
I don't think the current icon is the youtube logo anyway. I can't find evidence on the web this has ever been used:

<img src="https://raw.githubusercontent.com/edent/SuperTinyIcons/master/images/svg/youtube.svg">

Youtube's current logo is a red "TV shape" with a white triangle in its middle and the word "YouTube". It used to be just "YouTube" with the "Tube" a red TV shape:

https://www.youtube.com/watch?v=UyHutLa9Nx4

**Comment by Eiim** [comment]
So your concern is that the colors are inverted?

**Comment by wahyu6070** [comment]
![CGK](https://user-images.githubusercontent.com/47686437/168548113-b3cd4206-3281-445b-b7c6-bc0a3251293d.png)
