### ISSUE TITLE
Add size info of the gzipped version (.svgz)?

### ISSUE THREAD

**Issue by be5invis** [edent/SuperTinyIcons#64]

**Comment by edent** [comment]
It's an interesting suggestion - but there are a few problems.

1. .svgz can sometimes be *larger* than the raw .svg file. Take a look at the Dropbox SVG file.
2. Most browsers don't support .svgz natively.
3. Most servers will already gzip compress the files they send.

I'm happy to hear rebuttals to my argument :-)

**Comment by be5invis** [comment]
1. You can list both the sizes for comparison.
2. AFAIK all browsers support SVGZ if you provide proper HTTP headers.
3. The size would become a reference of the size of gzipped stream, or the actual bytes being delivered via the web.

**Comment by edent** [comment]
Could you run through the files and see whether SVGZ makes a difference in all cases, please?
