### ISSUE TITLE
kilobyte-svg-challenge

### ISSUE THREAD

**Issue by denilsonsa** [edent/SuperTinyIcons#706]
Many years ago, I found (and [contributed to](https://github.com/johan/kilobyte-svg-challenge/commits/master)) the https://github.com/johan/kilobyte-svg-challenge , a repository with the objective (or challenge) "Make an accurate SVG of a logo, in 1024 bytes or less!"

Today, I find your SuperTinyIcons repository, that seems to follow the same idea. I wonder if there is anything over there that could be imported over here. Or if a PR should be opened over there to make their README point to this repository.

**Comment by edent** [comment]
How interesting! I had no idea that existed. Feel free to see if there's anything which can be imported.

**Comment by denilsonsa** [comment]
Let's see… [27 logos](https://github.com/johan/kilobyte-svg-challenge/tree/master/logos):

* [betterlinks.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/betterlinks.svg) is a pretty and colorful logo, but [their service is gone since 2012 or 2013](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/betterlinks.svg).
* [britely.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/britely.svg) is [also gone since 2013](https://web.archive.org/web/20230000000000*/britely.com/).
* [chrome.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/chrome.svg) is the older gradient-shaded logo, instead of the modern [flat-shaded](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/chrome.svg)
* [cocacola.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/cocacola.svg) is missing here!
* [coderwall.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/coderwall.svg) is missing here! It looks like their logos from [their source-code on github](https://github.com/coderwall/coderwall-next/tree/master/public). I wrote that logo from scratch, but now I see [they have a SVG](https://github.com/coderwall/coderwall-next/blob/master/app/views/shared/_logo.html.erb), and [recently they changed the color for whatever reason](https://github.com/coderwall/coderwall-next/commit/0e7841a99166d1f4c4d0a1743b96accd967382f8).
* [facebook.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/facebook.svg) is [their older branding](https://github.com/edent/SuperTinyIcons/commit/e6f3387b9e894d69f2a2d0f42a0e83fdcb66cd97).
* [flickr.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/flickr.svg) is slightly smaller, with transparent background, when [compared to the one here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/flickr.svg). Not sure which one is better.
* [github-octocat.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/github-octocat.svg) is the fully-colored octocat mascot. This version is missing here.
* [github-social-coding.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/github-social-coding.svg) is a boring logo full of text, probably obsolete.
* [gits-sac-laughing-man.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/gits-sac-laughing-man.svg) is missing here! It's [an animated logo from Ghost In The Shell](https://ghostintheshell.fandom.com/wiki/Laughing_Man). It is exactly 1000 bytes.
* [globen-ogonklinik.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/globen-ogonklinik.svg) is a simple and nice-looking logo for what looks like an eye clinic. It's also [certainly obsolete](https://github.com/johan/kilobyte-svg-challenge/commit/7247747bee5bec735b23c24bbbfd3a3afeb00e4c).
* [googleplus.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/googleplus.svg) is slightly different from [the version here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/google_plus.svg). Either way, it's [gone since 2019](https://killedbygoogle.com/).
* [groupon.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/groupon.svg) seems to be an [old version](https://commons.wikimedia.org/wiki/File:Groupon_logo.svg) of [their logo](https://about.groupon.com/press/).
* [hackhands.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/hackhands.svg) is a nice logo, but [that platform shut down after being acquired by Pluralsight](https://www.pluralsight.com/hackhands).
* [html5.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/html5.svg) has the "HTML" text above the logo, when compared to [the version here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/html5.svg).
* [ie.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/ie.svg) is a nice SVG version of the obsolete Internet Explorer browser. And it's probably not accurate to the official logo.
* [ifttt.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/ifttt.svg) is [the old logo until 2016 or so](https://commons.wikimedia.org/wiki/Category:IFTTT).
* [ingress.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/ingress.svg) is the logo for [an online game that still exists](https://ingress.com/). The modern logo is possibly different, but I don't know. It is missing here!
* [lysator.svg](https://github.com/johan/kilobyte-svg-challenge/commits/master/logos/lysator.svg) is [an academic computer club](https://en.wikipedia.org/wiki/Lysator) [from Linköping, Sweden](https://www.lysator.liu.se/index_en.html).
* [opera.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/opera.svg) is the old logo for the Opera browser, when it still used the Presto engine. We have [the newer logo here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/opera.svg).
* [pike.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/pike.svg) which is apparently [from](https://pike.lysator.liu.se/download/logotype/img/pike_logo.svg) the [Pike programming language](https://pike.lysator.liu.se/). Amusingly, it has 6666 bytes.
* [pirate-party-sweden.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/pirate-party-sweden.svg) is exactly what it sounds like.
* [roxen.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/roxen.svg) is a nicely designed logo, but obsolete. And [probably only relevant to Scandinavia](https://www.roxen.com/).
* [simple.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/simple.svg) is a nice logo for a [defunct bank](https://en.wikipedia.org/wiki/Simple_(bank)).
* [simplymeasured.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/simplymeasured.svg) is a logo for [a startup that was acquired by another company](https://startupstash.com/tools/simply-measured/).
* [twitter.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/twitter.svg) is a smaller version of [what we have in this repository](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/twitter.svg). It's also reversed (blue bird on transparent background, instead of white bird on blue square). Not sure which one is more "correct".
* [webplatform.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/webplatform.svg) is a logo for [a project discontinued in 2015](https://webplatform.github.io/).

**Comment by denilsonsa** [comment]
Alternatively, in a table format:

| File/logo on [kilobyte-svg-challenge](https://github.com/johan/kilobyte-svg-challenge)                                   | | |
| - | - | - |
| [betterlinks.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/betterlinks.svg)                     | ~~here~~ | obsolete |
| [britely.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/britely.svg)                             | ~~here~~ | obsolete |
| [chrome.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/chrome.svg)                               | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/chrome.svg)      | obsolete |
| [cocacola.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/cocacola.svg)                           | ~~here~~ |          |
| [coderwall.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/coderwall.svg)                         | ~~here~~ |          |
| [facebook.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/facebook.svg)                           | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/facebook.svg)    | obsolete |
| [flickr.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/flickr.svg)                               | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/flickr.svg)      |          |
| [github-octocat.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/github-octocat.svg)               | ~~here~~ |          |
| [github-social-coding.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/github-social-coding.svg)   | ~~here~~ | obsolete |
| [gits-sac-laughing-man.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/gits-sac-laughing-man.svg) | ~~here~~ |          |
| [globen-ogonklinik.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/globen-ogonklinik.svg)         | ~~here~~ | obsolete |
| [googleplus.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/googleplus.svg)                       | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/google_plus.svg) | obsolete |
| [groupon.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/groupon.svg)                             | ~~here~~ | obsolete |
| [hackhands.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/hackhands.svg)                         | ~~here~~ | obsolete |
| [html5.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/html5.svg)                                 | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/html5.svg)       |          |
| [ie.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/ie.svg)                                       | ~~here~~ | obsolete |
| [ifttt.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/ifttt.svg)                                 | ~~here~~ | obsolete |
| [ingress.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/ingress.svg)                             | ~~here~~ |          |
| [lysator.svg](https://github.com/johan/kilobyte-svg-challenge/commits/master/logos/lysator.svg)                          | ~~here~~ |          |
| [opera.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/opera.svg)                                 | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/opera.svg)       | obsolete |
| [pike.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/pike.svg)                                   | ~~here~~ |          |
| [pirate-party-sweden.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/pirate-party-sweden.svg)     | ~~here~~ |          |
| [roxen.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/roxen.svg)                                 | ~~here~~ | obsolete |
| [simple.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/simple.svg)                               | ~~here~~ | obsolete |
| [simplymeasured.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/simplymeasured.svg)               | ~~here~~ | obsolete |
| [twitter.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/twitter.svg)                             | [here](https://github.com/edent/SuperTinyIcons/blob/master/images/svg/twitter.svg)     |          |
| [webplatform.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/webplatform.svg)                     | ~~here~~ | obsolete |

**Comment by kuubeu** [comment]
So excluding obsolete services/logos and icons already here, we're left with these:

File on [kilobyte-svg-challenge](https://github.com/johan/kilobyte-svg-challenge) | Size | Website/app logo?
-- | -- | --
[cocacola.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/cocacola.svg) | 2.61 KB | no
[coderwall.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/coderwall.svg) | 286 Bytes | yes
[github-octocat.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/github-octocat.svg) | 4.74 KB | no
[gits-sac-laughing-man.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/gits-sac-laughing-man.svg) | 1000 Bytes | no
[lysator.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/lysator.svg) | 1.71 KB | no
[pike.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/pike.svg) | 6.51 KB | no
[pirate-party-sweden.svg](https://github.com/johan/kilobyte-svg-challenge/blob/master/logos/pirate-party-sweden.svg) | 387 Bytes | no

Looks like the only logo meeting this repo's criteria is the Coderwall logo. I'll adapt it to meet the guidelines and close this issue. It's a very interesting project though!
