### ISSUE TITLE
VueJS logo not centered

### ISSUE THREAD

**Issue by ulyssear** [edent/SuperTinyIcons#725]
The vuejs logo is not centered like the other logo (see below).

NB : The expected logo has been taken from Wikimedia (https://commons.wikimedia.org/wiki/File:Vue.js_Logo_2.svg).

|  Current logo  | Expected logo |
|---|---|
| <img width=150 height=150 src="https://github.com/edent/SuperTinyIcons/assets/11415595/d3c8002f-1cb2-4b8a-90c3-736a50a99de9" /> | <img width=150 height=150 src="https://github.com/edent/SuperTinyIcons/assets/11415595/b4c307de-4eeb-4561-b2e2-bff994fd4ea4" /> |

**Comment by Eiim** [comment]
Fixed, thanks!
