### ISSUE TITLE
YouTube icon lettering is uneven

### ISSUE THREAD

**Issue by ryanscottaudio** [edent/SuperTinyIcons#73]
Particularly the `b` in Tube. The lettering is also pretty jagged.

**Comment by edent** [comment]
Yup - a consequence of minimisation. I'd be grateful if you can find a way to improve it :-)

**Comment by ryanscottaudio** [comment]
It seems like the icon you're supposed to use is actually https://www.youtube.com/yt/about/media/images/brand-resources/icons/YouTube-icon-our_icon.png anyway; maybe switch to that?

**Comment by edent** [comment]
Aha! A much better idea. Do you know if there's an SVG somewhere for reference?

**Comment by ryanscottaudio** [comment]
Seems like the only files they give for reference are in 
[here](https://github.com/edent/SuperTinyIcons/files/1506659/youtube_full_color_icon.zip) (from https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors under "The YouTube Icon"), and most of them are .png with no .svg in sight. Sorry...

**Comment by edent** [comment]
There's an EPS there I can use as a vector. Thanks!
