### ISSUE TITLE
Add Microsoft Azure logo

### ISSUE THREAD

**Issue by snehil2112** [edent/SuperTinyIcons#763]
## The icon I want is:

* Name: Microsoft Azure
* URL: https://azure.microsoft.com/en-in/
* Link to icon: https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Microsoft_Azure.svg/150px-Microsoft_Azure.svg.png

* Vector version of the logo: https://upload.wikimedia.org/wikipedia/commons/f/fa/Microsoft_Azure.svg
* Official style guide or brand guide:

**Comment by jmb** [comment]
I've tried to make a start here: https://github.com/jmb/SuperTinyIcons/blob/ms-azure/images/svg/azure.svg but have only managed 1591 bytes so far. The gradients are most likely the issue, even though I've rounded a lot of the values.

**Comment by Eiim** [comment]
If you can bake-in the gradientTransform and gradientUnits attributes, that should save a couple hundred bytes, but as far as I know you have to do that manually and it's a bit of a pain to do accurately. I might work on it if I have the time. Even then you'll be short, but it might be possible to make up the rest with path optimization and maybe even reducing the number of stops in the gradients.

**Comment by jmb** [comment]
I've given that a go and now have 1333 bytes. There must be some more optimisations to find! :)

**Comment by Eiim** [comment]
Mind sharing that version?

**Comment by jmb** [comment]
Down to 1243 bytes - in the ms-azure branch on my fork: https://github.com/jmb/SuperTinyIcons/tree/ms-azure
