### ISSUE TITLE
Update twitter icon at the README file

### ISSUE THREAD

**Issue by MohamedAli00949** [edent/SuperTinyIcons#772]
The Twitter icon in the readme file is not the new " X " icon.
That is important for the developers who search for the icon and find that you use the old icon.

**Comment by edent** [comment]
Sounds like you ought to send a PR to fix it :-)

**Comment by jmb** [comment]
The X logo is in there too, but maybe they should be labeled more clearly so that they're next to each other...

**Comment by MohamedAli00949** [comment]
@jmb Yes, I have seen the logo now while committing the updates. I will fix the error in the code and make the PR.
Thank you

**Comment by MohamedAli00949** [comment]
I am sorry, I have found the icon at the bottom. 
![Screenshot 2023-10-15 165336](https://github.com/edent/SuperTinyIcons/assets/76850143/3de34ce8-2dee-4f74-b324-4bc48eedf497)
The first time, I searched, I found the Twitter logo at the top.

**Comment by MohamedAli00949** [comment]
[](url)
