### ISSUE TITLE
Bug: Unable to use X icon even on latest version

### ISSUE THREAD

**Issue by siddheshranade** [edent/SuperTinyIcons#778]
My company's website (NextJS app) has links to Twitter in the footer, which uses the Twitter icon from this package like this:

```
import TwitterIcon from "super-tiny-icons/images/svg/twitter.svg";
```

This works perfectly. I wanted to change the Twitter icon to the X icon, to reflect the website's new change. However, this does not work:

```
import TwitterIcon from "super-tiny-icons/images/svg/x.svg";
```

It gives the `Module not found: Can't resolve 'super-tiny-icons/images/svg/x.svg'` error.

Two things to note:
1. It gives the same error on versions 0.4.0 and 0.5.0 of this package.
2. Every other icon I tried importing apart from X successfully works.

I think this is a bug. Let me know if I'm doing something wrong or if more info is needed.

**Comment by edent** [comment]
I've tried publishing a new version. Please let me know if 0.6.0 solves it.

**Comment by siddheshranade** [comment]
@edent Yes, that works, thank you!
