### ISSUE TITLE
Kickstarter Logo Broken

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#78]
![screen shot 2017-11-28 at 09 12 51](https://user-images.githubusercontent.com/837136/33311356-77e29252-d41c-11e7-9aa2-6a059d776242.png)

Seen on https://edent.github.io/SuperTinyIcons/radius.html

Works in Safari. Broken in Chrome and Firefox.

**Comment by RazrFalcon** [comment]
It's because of `clipPath`. New one should fix this.
