### ISSUE TITLE
Most of the icons doesn't follow the inner circle rule

### ISSUE THREAD

**Issue by RazrFalcon** [edent/SuperTinyIcons#81]
From readme:
>fit inside a circle with radius 256 pixels

**Comment by edent** [comment]
Looking at https://edent.github.io/SuperTinyIcons/radius.html the problems appear to be...

* RSS
* PDF
* LinkedIn
* Windows

Any others?

The following are designed to be square:

* HTML5
* Delicious
* Symantec

**Comment by RazrFalcon** [comment]
What about spacing? Some icons are smaller than 50% radius. For example spotify/wordpress probably 40-45%, FOSS is exactly 50%, gitlab/github is about 45%, etc.

Is it intended to be like this?

**Comment by RazrFalcon** [comment]
Yes. But currently we have maximum margin, but not minimum. Is it ok?

**Comment by edent** [comment]
I *think* so :-)

**Comment by himanshuxd** [comment]
Margin around the icons is fairly accurate right now imho, but could you please send me a link of the Microsoft tiny icon but with square/sharp edges instead of circular one ?

**Comment by arturoacevedob** [comment]
You can delete the `rx="15%"` in the file. That will get rid of the round corners.

**Comment by himanshuxd** [comment]
Worked perfectly, thanks @arturoacevedob

**Comment by edent** [comment]
Think this can be solved by using the guide in #86. Will work on it when / if I have time.
