### ISSUE TITLE
Vegetarian Logo Update

### ISSUE THREAD

**Issue by edent** [edent/SuperTinyIcons#813]
The current vegetarian logo is outdated. It needs to be replaced with this - https://commons.wikimedia.org/wiki/Category:V-Label#/media/File:Vegetarian-mark.svg - in a green circle.

**Comment by maxwithbug** [comment]
@edent trying this

**Comment by Eiim** [comment]
Note: we currently have three open pull requests addressing this issue (#814, #816, #819). Currently, none of them meet the requirements in [CONTRIBUTING.md](https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md). If you're attempting to update this logo (or any other), make sure you understand the requirements, check other existing logos as guidelines, and ask if you have any questions.

**Comment by maxwithbug** [comment]
can you please provide me image link with circle ?  is this https://commons.wikimedia.org/wiki/Category:V-Label#/media/File:Vegan_friendly_icon.png ok?
