### ISSUE TITLE
Performance and Animation Inconsistencies with 3D Table Effects and Hover Interactions

### ISSUE THREAD

**Issue by TusharNaugain** [edent/SuperTinyIcons#823]
The 3D perspective on table rows and cells causes rendering performance issues, particularly on lower-end devices. Hover effects on icons result in inconsistent animations due to the interaction between scaling and rotation. Mouse-based dynamic rotation occasionally leads to jittery transitions.

**Comment by edent** [comment]
This is a problem that you caused in https://github.com/edent/SuperTinyIcons/pull/822

Please don't add problems just to fix them.
