### ISSUE TITLE
Leetcode logo

### ISSUE THREAD

**Issue by kycilius** [edent/SuperTinyIcons#838]
## The icon I want is:

* Name: Leetcode
* URL: https://leetcode.com/
* Link to icon: ![leetcode icon](https://github.com/user-attachments/assets/04903ad6-a7d0-40b5-9f51-920ace991989)

@edent i want to add this can you please assign this to me with label hactoberfest :)

**Comment by edent** [comment]
@kycilius Please read https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

You can start working on this. Please ask questions *before* sending a PR.

**Comment by kycilius** [comment]
@edent sorry for that i will make sure that it will never happen again

**Comment by Sparsh2105** [comment]
Hello sir pls assign me this issue

**Comment by kycilius** [comment]
I have submitted it bro

**Comment by kycilius** [comment]
thanks @edent sir
