### ISSUE TITLE
Hacktober Fest

### ISSUE THREAD

**Issue by kycilius** [edent/SuperTinyIcons#839]
Are pull requests in this repository getting considered for hacktoberfest?

**Comment by edent** [comment]
Yes. Valid pull requests will be accepted. Read https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md

**Comment by edent** [comment]
You haven't submitted any code, have you?

You closed your own issue. You can re-open it, and then submit a PR.

**Comment by kycilius** [comment]
I have submitted the issue by the name of leetcode

**Comment by edent** [comment]
You have submitted an issue. That's a great first start. Now you need to fork this repository, add your code, and send a Pull Request. Good luck 😃
