### ISSUE TITLE
Add Gemini Logo

### ISSUE THREAD

**Issue by ohmschrodinger** [edent/SuperTinyIcons#847]
## The icon I want is:

* Name: Gemini
* URL: https://gemini.google.com/
* Link to icon: https://www.freelogovectors.net/gemini-logo-chatbot-01/

* Vector version of the logo: https://github.com/ohmschrodinger/Hacktober-Fest-2024/blob/main/gemini.svg

**Comment by ohmschrodinger** [comment]
@edent  I've read through the https://github.com/edent/SuperTinyIcons/blob/master/CONTRIBUTING.md and I've committed the changes to my forked repo. Should I go ahead and send a PR? Is that okay?

**Comment by ohmschrodinger** [comment]
In case you need a reference, here’s the link to my forked repository: 
[https://github.com/ohmschrodinger/SuperTinyIcons/tree/GeminiLogo?tab=readme-ov-file](url)

**Comment by ohmschrodinger** [comment]
It's done. do i need to make any other changes?

**Comment by edent** [comment]
I can't see it any more. Send it as a PR to this repository.
