### ISSUE TITLE
Add Rockstar Games Logo

### ISSUE THREAD

**Issue by Sattwik-8** [edent/SuperTinyIcons#855]
## The icon I want is:

* Name: Rockstar Games
* URL: https://www.rockstargames.com/
* Link to icon: https://www.freelogovectors.net/rockstar-games-logo-eps-pdf-files/

**@edent, Please add me under Hacktober Fest**

**Comment by edent** [comment]
@Sattwik-8 **please read the Contributing guide**

**Comment by Sattwik-8** [comment]
@edent Thank you for letting me know about the contribution guide.

**Comment by edent** [comment]
Fixed in #856
