### ISSUE TITLE
Icons should follow a visual guideline.

### ISSUE THREAD

**Issue by arturoacevedob** [edent/SuperTinyIcons#86]
Having a detailed visual guideline would make all icons consistent and save a lot of time of tweaking. Seems that some icons were sized for a specific shape in mind, ones for a rounded square, others for circles or for visibility at small sizes. Most noticeable at https://edent.github.io/SuperTinyIcons/radius.html. Therefore I propose this:

![layer 1 0 5x](https://user-images.githubusercontent.com/19752150/33352352-142a250c-d46e-11e7-9ed2-4cff9b8314ab.png)

This helps with sizing for both square and circle icons, so they would look good no matter what radius is chosen.

- Green (75% of canvas) is the safe zone, where the main body of the icon should be.
- Yellow (85% of canvas) is like a road shoulder, it's there if more space is needed. It should be used for protruding elements, like corners or ornaments.
- Red is off limits. It should not be touched by the icons. Red is also how a circular icon would look.

One problem with sizing for both squares and circles, is that some icons, due to their nature, might end up a bit small for good visibility when displayed at very, very small sizes in square form. Needless to say, these are just guides. If they don't accommodate a certain shape, then they shouldn't be followed strictly. 

In those cases, it may be better for the user to make adjustments for their very, very small square icons. But, just for the sake of it, I also propose this guideline for them or us to use:

![guidelines for small sizes 0 5x](https://user-images.githubusercontent.com/19752150/33352625-748b9b00-d46f-11e7-8bc8-be8543fc28c5.png)

Colors represent the same thing. Except the percentages.

The SVGs are the following:

`<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" aria-label="Guideline" role="img">
	<rect fill="#222" height="512" rx="15%" width="512"/>
	<rect fill="#ff3f32" height="512" rx="50%" width="512"/>
	<rect fill="#ffd900" height="435" rx="50%" width="435" x="39" y="39"/>
	<rect fill="#4cd966" height="384" rx="50%" width="384" x="64" y="64"/>
</svg>`

`<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" aria-label="Guideline for small square" role="img">
	<rect fill="#222" height="512" rx="15%" width="512"/>
	<rect fill="#ff3f32" height="512" rx="30%" width="512"/>
	<rect fill="#ffd900" height="512" rx="40%" width="512"/>
	<rect fill="#4cd966" height="448" rx="40%" width="448" x="32" y="32"/>
</svg>`

**Comment by olivesayang** [comment]
<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" aria-label="Guidelines" role="img"> <rect fill="#222" height="512" rx="15%" width="512"/> <rect fill="#ff3f32" height="512" rx="50%" width="512"/> <rect fill="#ffd900" height="435" rx="50%" width="435" x="39" y="39"/> <rect fill="#4cd966" height="384" rx="50%" width="384" x="64" y="64"/> </svg>

<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" aria-label="Guidelines" role="img"> <rect fill="#222" height="512" rx="15%" width="512"/> <rect fill="#ff3f32" height="512" rx="30%" width="512"/> <rect fill="#ffd900" height="512" rx="40%" width="512"/> <rect fill="#4cd966" height="448" rx="40%" width="448" x="32" y="32"/> </svg>

**Comment by edent** [comment]
Looks good!

**Comment by edent** [comment]
OK! So, the next task is...

1. For every icon
1. Compare them at https://github.com/edent/SuperTinyIcons/blob/master/images/reference/index.md 
1. Make them fit in the guide

Go! Go! Go!
