### ISSUE TITLE
Add TATA icon

### ISSUE THREAD

**Issue by ohmschrodinger** [edent/SuperTinyIcons#871]
## The icon I want is:

* Name: Tata Groups
* URL: https://www.tata.com/
* Link to icon: [https://commons.wikimedia.org/wiki/File:Tata_logo.svg](url) 

* Vector version of the logo: [https://github.com/ohmschrodinger/Hacktober-Fest-2024/blob/main/Tata.svg](url)

**Comment by ohmschrodinger** [comment]
@edent  i've read the CONTRIBUTING.MD file and made the changes to my local repo, please acknowledge.

heres the link to my forked repo
[https://github.com/ohmschrodinger/SuperTinyIcons/tree/TATA](url)

**Comment by edent** [comment]
* You don't need a reference svg and png. Just one will do.
* Your reference image needs to come from the official website, don't just re-use your SVG.
* Your reference URl is empty.
* The links in the above comments don't work. I'm not sure what you're doing to them.

**Comment by ohmschrodinger** [comment]
okay ill make the necessary changes

ps- please copy paste the link in your browser
