### ISSUE TITLE
Google Play image

### ISSUE THREAD

**Issue by MaG21** [edent/SuperTinyIcons#90]
Please consider making a svg for the Google Play logo

**Comment by edent** [comment]
Can you find a good vector source for it please?

**Comment by MaG21** [comment]
Maybe

Is it possible to use the svg glyphs from a free font like _Font Awesome_?

**Comment by MaG21** [comment]
For example, I took these from font Awesome. Can you use them (they need colours though)? they're under 2KB

![chrome](https://user-images.githubusercontent.com/1760771/33433818-79bb94e6-d5b3-11e7-8540-233c97f760fc.png)
![skype](https://user-images.githubusercontent.com/1760771/33433819-79d41bd8-d5b3-11e7-98d7-cb0c8fb5655b.png)
![slack](https://user-images.githubusercontent.com/1760771/33433820-79ea7eaa-d5b3-11e7-9115-348be99e29bd.png)

**Comment by edent** [comment]
None of those icons are for Google Play. I'm happy to make a Super Tiny Icon - but I need you to find me a high quality one to work from.
